// AUTO-GENERATED by scripts/build-ambience.ts — 직접 수정 금지.
// 재생성: npx tsx scripts/build-ambience.ts
/**
 * 백색소음 채널 — 채널당 1곡을 심리스 루프로 반복 재생한다.
 *
 * 음원 출처 (Wikimedia Commons):
 * - 빗소리: Zuvji — CC BY-SA 4.0 (https://commons.wikimedia.org/wiki/File:Calm_rain.wav)
 * - 숲속: Silas S. Brown — Public Domain (https://commons.wikimedia.org/wiki/File:Dawnchorus-uk.ogg)
 * - 파도: Andrew Migneault — CC BY-SA 4.0 (https://commons.wikimedia.org/wiki/File:Lake_Okeechobee_Surf_in_April_2016.ogg)
 * - 모닥불: Glaneur de sons — CC BY 3.0 (https://commons.wikimedia.org/wiki/File:Campfire_sound_ambience.ogg)
 */
import type { MusicGenre } from "@/types/music";

export const AMBIENCE_GENRES: MusicGenre[] = [
  {
    "id": "rain",
    "name": "빗소리",
    "emoji": "🌧️",
    "ambience": true,
    "tracks": [
      {
        "title": "잔잔한 빗소리",
        "composer": "Zuvji",
        "url": "/music/ambience-rain.mp3",
        "duration": 478
      }
    ]
  },
  {
    "id": "forest",
    "name": "숲속",
    "emoji": "🌲",
    "ambience": true,
    "tracks": [
      {
        "title": "새벽 숲의 새소리",
        "composer": "Silas S. Brown",
        "url": "/music/ambience-forest.mp3",
        "duration": 478
      }
    ]
  },
  {
    "id": "waves",
    "name": "파도",
    "emoji": "🌊",
    "ambience": true,
    "tracks": [
      {
        "title": "밀려오는 파도",
        "composer": "Andrew Migneault",
        "url": "/music/ambience-waves.mp3",
        "duration": 323
      }
    ]
  },
  {
    "id": "fire",
    "name": "모닥불",
    "emoji": "🔥",
    "ambience": true,
    "tracks": [
      {
        "title": "타닥이는 모닥불",
        "composer": "Glaneur de sons",
        "url": "/music/ambience-fire.mp3",
        "duration": 58
      }
    ]
  }
];
