// AUTO-GENERATED by scripts/build-combined-music.ts — 직접 수정 금지.
// 재생성: npx tsx scripts/build-combined-music.ts
import type { MusicGenre } from "@/types/music";

export const MUSIC_GENRES: MusicGenre[] = [
  {
    "id": "classic",
    "name": "클래식",
    "emoji": "🎻",
    "durationSeconds": 16775.627,
    "parts": [
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/classic-1.mp3",
        "start": 0,
        "duration": 2705.371
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/classic-2.mp3",
        "start": 2705.371,
        "duration": 2451.984
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/classic-3.mp3",
        "start": 5157.355,
        "duration": 2646.23
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/classic-4.mp3",
        "start": 7803.585,
        "duration": 2877.727
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/classic-5.mp3",
        "start": 10681.312,
        "duration": 2691.291
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/classic-6.mp3",
        "start": 13372.603,
        "duration": 2916.676
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/classic-7.mp3",
        "start": 16289.279,
        "duration": 486.348
      }
    ],
    "cues": [
      {
        "title": "골드베르크 변주곡 - Aria",
        "composer": "바흐",
        "start": 0,
        "duration": 292.467
      },
      {
        "title": "골드베르크 변주곡 - Var.25",
        "composer": "바흐",
        "start": 292.467,
        "duration": 410.54
      },
      {
        "title": "평균율 1권 프렐류드 C장조 BWV 846",
        "composer": "바흐",
        "start": 703.007,
        "duration": 318.38
      },
      {
        "title": "무반주 첼로 모음곡 1번 - 프렐류드",
        "composer": "바흐",
        "start": 1021.388,
        "duration": 150.465
      },
      {
        "title": "캐논 D장조",
        "composer": "파헬벨",
        "start": 1171.853,
        "duration": 462.08
      },
      {
        "title": "양은 풀을 뜯고 (BWV 208)",
        "composer": "바흐",
        "start": 1633.933,
        "duration": 301.427
      },
      {
        "title": "수상음악 - 알라 호른파이프",
        "composer": "헨델",
        "start": 1935.36,
        "duration": 222.616
      },
      {
        "title": "라르고 (옴브라 마이 푸)",
        "composer": "헨델",
        "start": 2157.975,
        "duration": 219.35
      },
      {
        "title": "월광 소나타 - 1악장",
        "composer": "베토벤",
        "start": 2377.326,
        "duration": 328.046
      },
      {
        "title": "아이네 클라이네 - 2악장 Romance",
        "composer": "모차르트",
        "start": 2705.371,
        "duration": 364.513
      },
      {
        "title": "교향곡 40번 - 2악장 Andante",
        "composer": "모차르트",
        "start": 3069.884,
        "duration": 456.202
      },
      {
        "title": "교향곡 3번 에로이카 - 2악장",
        "composer": "베토벤",
        "start": 3526.086,
        "duration": 928.549
      },
      {
        "title": "아이네 클라이네 나흐트무지크 - 1악장 Allegro",
        "composer": "모차르트",
        "start": 4454.635,
        "duration": 343.876
      },
      {
        "title": "교향곡 40번 - 1악장 Molto Allegro",
        "composer": "모차르트",
        "start": 4798.511,
        "duration": 358.844
      },
      {
        "title": "교향곡 5번 - 1악장 운명",
        "composer": "베토벤",
        "start": 5157.355,
        "duration": 500.114
      },
      {
        "title": "교향곡 7번 - 4악장 Allegro con brio",
        "composer": "베토벤",
        "start": 5657.469,
        "duration": 390.661
      },
      {
        "title": "피아노 협주곡 21번 - 2악장 Andante",
        "composer": "모차르트",
        "start": 6048.13,
        "duration": 498.233
      },
      {
        "title": "세빌리아의 이발사 서곡",
        "composer": "로시니",
        "start": 6546.364,
        "duration": 440.555
      },
      {
        "title": "교향곡 7번 - 2악장 Allegretto",
        "composer": "베토벤",
        "start": 6986.919,
        "duration": 489.744
      },
      {
        "title": "비창 소나타 - 2악장 Adagio",
        "composer": "베토벤",
        "start": 7476.662,
        "duration": 326.922
      },
      {
        "title": "교향곡 25번 - 1악장",
        "composer": "모차르트",
        "start": 7803.585,
        "duration": 475.089
      },
      {
        "title": "소나타 D.664 - 1악장",
        "composer": "슈베르트",
        "start": 8278.674,
        "duration": 466.207
      },
      {
        "title": "소나타 D.664 - 2악장",
        "composer": "슈베르트",
        "start": 8744.881,
        "duration": 290.873
      },
      {
        "title": "녹턴 Op.9 No.2",
        "composer": "쇼팽",
        "start": 9035.755,
        "duration": 276.637
      },
      {
        "title": "녹턴 Op.27 No.2",
        "composer": "쇼팽",
        "start": 9312.391,
        "duration": 377.809
      },
      {
        "title": "발라드 1번 Op.23",
        "composer": "쇼팽",
        "start": 9690.2,
        "duration": 613.616
      },
      {
        "title": "왈츠 Op.64 No.2",
        "composer": "쇼팽",
        "start": 10303.816,
        "duration": 230.087
      },
      {
        "title": "프렐류드 Op.28 No.4",
        "composer": "쇼팽",
        "start": 10533.903,
        "duration": 147.409
      },
      {
        "title": "프렐류드 Op.28 No.15 \"빗방울\"",
        "composer": "쇼팽",
        "start": 10681.312,
        "duration": 295.288
      },
      {
        "title": "현악 사중주 2번 - 녹턴",
        "composer": "보로딘",
        "start": 10976.6,
        "duration": 547.396
      },
      {
        "title": "아메리칸 사중주 - Lento",
        "composer": "드보르작",
        "start": 11523.996,
        "duration": 471.51
      },
      {
        "title": "명상곡",
        "composer": "수크",
        "start": 11995.506,
        "duration": 405.499
      },
      {
        "title": "페르 귄트 - 아침 기분",
        "composer": "그리그",
        "start": 12401.005,
        "duration": 229.224
      },
      {
        "title": "페르 귄트 - 오세의 죽음",
        "composer": "그리그",
        "start": 12630.229,
        "duration": 273.842
      },
      {
        "title": "타이스의 명상곡",
        "composer": "마스네",
        "start": 12904.071,
        "duration": 257.123
      },
      {
        "title": "백조 (동물의 사육제)",
        "composer": "생상스",
        "start": 13161.194,
        "duration": 211.409
      },
      {
        "title": "아베 마리아",
        "composer": "슈베르트",
        "start": 13372.603,
        "duration": 260.807
      },
      {
        "title": "녹턴 Op.15 No.2",
        "composer": "쇼팽",
        "start": 13633.41,
        "duration": 136.02
      },
      {
        "title": "녹턴 Op.55 No.1",
        "composer": "쇼팽",
        "start": 13769.429,
        "duration": 216.816
      },
      {
        "title": "트로이메라이 (꿈)",
        "composer": "슈만",
        "start": 13986.245,
        "duration": 152.869
      },
      {
        "title": "꿈 후에 (Après un rêve)",
        "composer": "포레",
        "start": 14139.114,
        "duration": 174.472
      },
      {
        "title": "헝가리 무곡 5번",
        "composer": "브람스",
        "start": 14313.586,
        "duration": 172.565
      },
      {
        "title": "꽃의 왈츠 (호두까기 인형)",
        "composer": "차이콥스키",
        "start": 14486.151,
        "duration": 405.368
      },
      {
        "title": "산왕의 궁전에서 (페르 귄트)",
        "composer": "그리그",
        "start": 14891.519,
        "duration": 155.063
      },
      {
        "title": "즉흥곡 Op.90 No.3",
        "composer": "슈베르트",
        "start": 15046.582,
        "duration": 404.48
      },
      {
        "title": "아라베스크 1번",
        "composer": "드뷔시",
        "start": 15451.062,
        "duration": 469.734
      },
      {
        "title": "달빛 (베르가마스크 모음곡)",
        "composer": "드뷔시",
        "start": 15920.796,
        "duration": 368.483
      },
      {
        "title": "짐노페디 1번",
        "composer": "사티",
        "start": 16289.279,
        "duration": 216.947
      },
      {
        "title": "뇨시엔느 1번",
        "composer": "사티",
        "start": 16506.226,
        "duration": 269.401
      }
    ]
  },
  {
    "id": "jazz",
    "name": "재즈",
    "emoji": "🎷",
    "durationSeconds": 4085.837,
    "parts": [
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/jazz-1.mp3",
        "start": 0,
        "duration": 2921.325
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/jazz-2.mp3",
        "start": 2921.325,
        "duration": 1164.512
      }
    ],
    "cues": [
      {
        "title": "Beautiful Dream",
        "composer": "Diego Nava",
        "start": 0,
        "duration": 97.045
      },
      {
        "title": "Latin Lovers",
        "composer": "Ahjay Stelino",
        "start": 97.045,
        "duration": 95.138
      },
      {
        "title": "Romantic 01",
        "composer": "Lily J",
        "start": 192.183,
        "duration": 98.717
      },
      {
        "title": "Romantic Vacation",
        "composer": "Ahjay Stelino",
        "start": 290.9,
        "duration": 111.752
      },
      {
        "title": "Smooth Like Jazz",
        "composer": "Ahjay Stelino",
        "start": 402.651,
        "duration": 158.302
      },
      {
        "title": "Chill Bro",
        "composer": "Diego Nava",
        "start": 560.953,
        "duration": 99.892
      },
      {
        "title": "Lounging By Moonlight",
        "composer": "Ahjay Stelino",
        "start": 660.846,
        "duration": 94.328
      },
      {
        "title": "Soul Jazz",
        "composer": "Francisco Alvear",
        "start": 755.174,
        "duration": 134.687
      },
      {
        "title": "Lonely in the Bar",
        "composer": "Diego Nava",
        "start": 889.861,
        "duration": 91.925
      },
      {
        "title": "Winter Wind",
        "composer": "Diego Nava",
        "start": 981.786,
        "duration": 91.899
      },
      {
        "title": "Jazz 1",
        "composer": "Francisco Alvear",
        "start": 1073.685,
        "duration": 133.982
      },
      {
        "title": "Nostalgic Night",
        "composer": "Michael Ramir C.",
        "start": 1207.667,
        "duration": 124.865
      },
      {
        "title": "Lo-Fi 03",
        "composer": "Lily J",
        "start": 1332.532,
        "duration": 113.371
      },
      {
        "title": "Swing is the Answer",
        "composer": "Diego Nava",
        "start": 1445.903,
        "duration": 108.8
      },
      {
        "title": "Where Are My Boots",
        "composer": "Michael Ramir C.",
        "start": 1554.703,
        "duration": 161.489
      },
      {
        "title": "Lost in a Dream",
        "composer": "Michael Ramir C.",
        "start": 1716.192,
        "duration": 111.491
      },
      {
        "title": "Papa",
        "composer": "Michael Ramir C.",
        "start": 1827.683,
        "duration": 96.627
      },
      {
        "title": "You Got Jazz",
        "composer": "Diego Nava",
        "start": 1924.31,
        "duration": 99.736
      },
      {
        "title": "Pop 03",
        "composer": "Grigoriy Nuzhny",
        "start": 2024.045,
        "duration": 171.363
      },
      {
        "title": "Upbeat Jazz",
        "composer": "Francisco Alvear",
        "start": 2195.408,
        "duration": 110.263
      },
      {
        "title": "Fun Jazz",
        "composer": "Francisco Alvear",
        "start": 2305.671,
        "duration": 140.643
      },
      {
        "title": "Slow Walk",
        "composer": "Michael Ramir C.",
        "start": 2446.314,
        "duration": 102.583
      },
      {
        "title": "Feeling Good",
        "composer": "Diego Nava",
        "start": 2548.897,
        "duration": 99.553
      },
      {
        "title": "Groovy Jazz",
        "composer": "Francisco Alvear",
        "start": 2648.45,
        "duration": 136.438
      },
      {
        "title": "Dreamy Jazz",
        "composer": "Francisco Alvear",
        "start": 2784.887,
        "duration": 136.438
      },
      {
        "title": "Close the Lights",
        "composer": "Michael Ramir C.",
        "start": 2921.325,
        "duration": 116.506
      },
      {
        "title": "Space Bird",
        "composer": "Diego Nava",
        "start": 3037.831,
        "duration": 109.453
      },
      {
        "title": "Funk Jazz",
        "composer": "Francisco Alvear",
        "start": 3147.284,
        "duration": 136.49
      },
      {
        "title": "Romantic 02",
        "composer": "Lily J",
        "start": 3283.774,
        "duration": 103.68
      },
      {
        "title": "Lost in Dreams",
        "composer": "Ahjay Stelino",
        "start": 3387.454,
        "duration": 124.108
      },
      {
        "title": "Red Moon",
        "composer": "Diego Nava",
        "start": 3511.562,
        "duration": 104.516
      },
      {
        "title": "Majestic",
        "composer": "Diego Nava",
        "start": 3616.077,
        "duration": 108.748
      },
      {
        "title": "Im Hungry",
        "composer": "Michael Ramir C.",
        "start": 3724.825,
        "duration": 110.002
      },
      {
        "title": "Yo Chucky",
        "composer": "Michael Ramir C.",
        "start": 3834.827,
        "duration": 96.862
      },
      {
        "title": "Pop 05",
        "composer": "Grigoriy Nuzhny",
        "start": 3931.689,
        "duration": 154.149
      }
    ]
  }
];
