// AUTO-GENERATED by scripts/build-music.ts — 직접 수정 금지.
// 재생성: npx tsx scripts/build-music.ts
import type { MusicGenre } from "@/types/music";

export const MUSIC_GENRES: MusicGenre[] = [
  {
    "id": "piano",
    "name": "피아노",
    "emoji": "🎹",
    "tracks": [
      {
        "title": "골드베르크 변주곡 - Aria",
        "composer": "바흐",
        "url": "/music/bach-goldberg-aria.mp3",
        "duration": 297.581
      },
      {
        "title": "골드베르크 변주곡 - Var.25",
        "composer": "바흐",
        "url": "/music/bach-goldberg-var25.mp3",
        "duration": 410.507
      },
      {
        "title": "평균율 1권 프렐류드 C장조 BWV 846",
        "composer": "바흐",
        "url": "/music/bach-wtc-prelude-c.mp3",
        "duration": 161.974
      },
      {
        "title": "프랑스 모음곡 5번 - 사라방드",
        "composer": "바흐",
        "url": "/music/bach-french-suite-5-sarabande.mp3",
        "duration": 226.274
      },
      {
        "title": "인벤션 1번 C장조",
        "composer": "바흐",
        "url": "/music/bach-invention-1-c-major.mp3",
        "duration": 64.07
      },
      {
        "title": "인벤션 8번 F장조",
        "composer": "바흐",
        "url": "/music/bach-invention-8-f-major.mp3",
        "duration": 54.574
      },
      {
        "title": "소나타 K.380",
        "composer": "스카를라티",
        "url": "/music/scarlatti-sonata-k380.mp3",
        "duration": 327.47
      },
      {
        "title": "월광 소나타 - 1악장",
        "composer": "베토벤",
        "url": "/music/beethoven-moonlight-1.mp3",
        "duration": 320.066
      },
      {
        "title": "비창 소나타 - 2악장 Adagio",
        "composer": "베토벤",
        "url": "/music/beethoven-pathetique-2-adagio.mp3",
        "duration": 321.046
      },
      {
        "title": "소나타 K.545 - 2악장 Andante",
        "composer": "모차르트",
        "url": "/music/mozart-sonata-k545-andante.mp3",
        "duration": 196.245
      },
      {
        "title": "소나타 D.664 - 1악장",
        "composer": "슈베르트",
        "url": "/music/schubert-allegro.mp3",
        "duration": 464.283
      },
      {
        "title": "소나타 D.664 - 2악장",
        "composer": "슈베르트",
        "url": "/music/schubert-andante.mp3",
        "duration": 289.19
      },
      {
        "title": "녹턴 Op.9 No.2",
        "composer": "쇼팽",
        "url": "/music/chopin-nocturne-op9-2.mp3",
        "duration": 268.57
      },
      {
        "title": "녹턴 Op.27 No.2",
        "composer": "쇼팽",
        "url": "/music/chopin-nocturne-op27-2.mp3",
        "duration": 366.552
      },
      {
        "title": "녹턴 Op.15 No.2",
        "composer": "쇼팽",
        "url": "/music/chopin-nocturne-op15-2.mp3",
        "duration": 230.331
      },
      {
        "title": "녹턴 Op.55 No.1",
        "composer": "쇼팽",
        "url": "/music/chopin-nocturne-op55-1.mp3",
        "duration": 310.918
      },
      {
        "title": "녹턴 Op.48 No.1",
        "composer": "쇼팽",
        "url": "/music/chopin-nocturne-op48-1.mp3",
        "duration": 367.616
      },
      {
        "title": "발라드 1번 Op.23",
        "composer": "쇼팽",
        "url": "/music/chopin-ballade-1.mp3",
        "duration": 611.639
      },
      {
        "title": "왈츠 Op.64 No.2",
        "composer": "쇼팽",
        "url": "/music/chopin-waltz-op64-2.mp3",
        "duration": 227.79
      },
      {
        "title": "프렐류드 Op.28 No.4",
        "composer": "쇼팽",
        "url": "/music/chopin-prelude-op28-4.mp3",
        "duration": 112.303
      },
      {
        "title": "프렐류드 Op.28 No.15 \"빗방울\"",
        "composer": "쇼팽",
        "url": "/music/chopin-prelude-op28-15.mp3",
        "duration": 312.669
      },
      {
        "title": "아베 마리아",
        "composer": "슈베르트",
        "url": "/music/schubert-ave-maria.mp3",
        "duration": 249.511
      },
      {
        "title": "즉흥곡 Op.90 No.3",
        "composer": "슈베르트",
        "url": "/music/schubert-impromptu-op90-3.mp3",
        "duration": 403.155
      },
      {
        "title": "트로이메라이 (꿈)",
        "composer": "슈만",
        "url": "/music/schumann-traumerei.mp3",
        "duration": 152.844
      },
      {
        "title": "꿈 후에 (Après un rêve)",
        "composer": "포레",
        "url": "/music/faure-apres-un-reve.mp3",
        "duration": 174.447
      },
      {
        "title": "위안 3번",
        "composer": "리스트",
        "url": "/music/liszt-consolation-3.mp3",
        "duration": 283.136
      },
      {
        "title": "아라베스크 1번",
        "composer": "드뷔시",
        "url": "/music/debussy-arabesque-1.mp3",
        "duration": 255.344
      },
      {
        "title": "달빛 (베르가마스크 모음곡)",
        "composer": "드뷔시",
        "url": "/music/debussy-clair-de-lune.mp3",
        "duration": 300.544
      },
      {
        "title": "짐노페디 1번",
        "composer": "사티",
        "url": "/music/satie-gymnopedie-1.mp3",
        "duration": 212.247
      },
      {
        "title": "뇨시엔느 1번",
        "composer": "사티",
        "url": "/music/satie-gnossienne-1.mp3",
        "duration": 265.375
      }
    ]
  },
  {
    "id": "classic",
    "name": "클래식",
    "emoji": "🎻",
    "tracks": [
      {
        "title": "무반주 첼로 모음곡 1번 - 프렐류드",
        "composer": "바흐",
        "url": "/music/bach-cello-suite-1-prelude.mp3",
        "duration": 146.491
      },
      {
        "title": "캐논 D장조",
        "composer": "파헬벨",
        "url": "/music/pachelbel-canon-d.mp3",
        "duration": 457.95
      },
      {
        "title": "양은 풀을 뜯고 (BWV 208)",
        "composer": "바흐",
        "url": "/music/bach-sheep-may-safely-graze.mp3",
        "duration": 290.498
      },
      {
        "title": "예수, 인간 소망의 기쁨",
        "composer": "바흐",
        "url": "/music/bach-jesu-joy-bwv147.mp3",
        "duration": 204.512
      },
      {
        "title": "아다지오 G단조",
        "composer": "알비노니",
        "url": "/music/albinoni-adagio-g-minor.mp3",
        "duration": 703.886
      },
      {
        "title": "라르고 (옴브라 마이 푸)",
        "composer": "헨델",
        "url": "/music/handel-largo-ombra-mai-fu.mp3",
        "duration": 212.614
      },
      {
        "title": "수상음악 - 에어",
        "composer": "헨델",
        "url": "/music/handel-water-music-air.mp3",
        "duration": 145.317
      },
      {
        "title": "무반주 플루트 환상곡 1번",
        "composer": "텔레만",
        "url": "/music/telemann-fantasia-1.mp3",
        "duration": 462.8
      },
      {
        "title": "정령들의 춤",
        "composer": "글루크",
        "url": "/music/gluck-dance-blessed-spirits.mp3",
        "duration": 382.824
      },
      {
        "title": "세레나데 (현악 사중주 Op.3-5)",
        "composer": "하이든",
        "url": "/music/haydn-serenade-andante.mp3",
        "duration": 233.137
      },
      {
        "title": "아이네 클라이네 - 2악장 Romance",
        "composer": "모차르트",
        "url": "/music/mozart-eine-kleine-2-romance.mp3",
        "duration": 364.484
      },
      {
        "title": "교향곡 40번 - 2악장 Andante",
        "composer": "모차르트",
        "url": "/music/mozart-symphony40-2.mp3",
        "duration": 454.81
      },
      {
        "title": "피아노 협주곡 21번 - 2악장 Andante",
        "composer": "모차르트",
        "url": "/music/mozart-piano-concerto-21-andante.mp3",
        "duration": 495.598
      },
      {
        "title": "교향곡 3번 에로이카 - 2악장",
        "composer": "베토벤",
        "url": "/music/beethoven-eroica-2.mp3",
        "duration": 925.166
      },
      {
        "title": "교향곡 7번 - 2악장 Allegretto",
        "composer": "베토벤",
        "url": "/music/beethoven-symphony7-2-allegretto.mp3",
        "duration": 489.607
      },
      {
        "title": "현악 사중주 2번 - 녹턴",
        "composer": "보로딘",
        "url": "/music/borodin-nocturne.mp3",
        "duration": 546.571
      },
      {
        "title": "아메리칸 사중주 - Lento",
        "composer": "드보르작",
        "url": "/music/dvorak-lento.mp3",
        "duration": 469.142
      },
      {
        "title": "명상곡",
        "composer": "수크",
        "url": "/music/suk-meditation.mp3",
        "duration": 404.355
      },
      {
        "title": "페르 귄트 - 아침 기분",
        "composer": "그리그",
        "url": "/music/grieg-morning-mood.mp3",
        "duration": 227.502
      },
      {
        "title": "페르 귄트 - 오세의 죽음",
        "composer": "그리그",
        "url": "/music/grieg-aases-death.mp3",
        "duration": 268.935
      },
      {
        "title": "타이스의 명상곡",
        "composer": "마스네",
        "url": "/music/massenet-thais-meditation.mp3",
        "duration": 255.815
      },
      {
        "title": "백조 (동물의 사육제)",
        "composer": "생상스",
        "url": "/music/saint-saens-the-swan.mp3",
        "duration": 204.749
      },
      {
        "title": "파반",
        "composer": "포레",
        "url": "/music/faure-pavane.mp3",
        "duration": 427.476
      },
      {
        "title": "보칼리제",
        "composer": "라흐마니노프",
        "url": "/music/rachmaninoff-vocalise.mp3",
        "duration": 333.345
      },
      {
        "title": "브란덴부르크 협주곡 3번 - 1악장",
        "composer": "바흐",
        "url": "/music/bach-brandenburg-3-allegro.mp3",
        "duration": 315.46
      },
      {
        "title": "토카타와 푸가 D단조",
        "composer": "바흐",
        "url": "/music/bach-toccata-fugue-d-minor.mp3",
        "duration": 520.571
      },
      {
        "title": "수상음악 - 알라 호른파이프",
        "composer": "헨델",
        "url": "/music/handel-water-music-alla-hornpipe.mp3",
        "duration": 226.384
      },
      {
        "title": "아이네 클라이네 나흐트무지크 - 1악장 Allegro",
        "composer": "모차르트",
        "url": "/music/mozart-eine-kleine-1-allegro.mp3",
        "duration": 348.499
      },
      {
        "title": "교향곡 40번 - 1악장 Molto Allegro",
        "composer": "모차르트",
        "url": "/music/mozart-symphony40-1.mp3",
        "duration": 358.359
      },
      {
        "title": "교향곡 25번 - 1악장",
        "composer": "모차르트",
        "url": "/music/mozart-symphony25-1.mp3",
        "duration": 469.088
      },
      {
        "title": "터키 행진곡",
        "composer": "모차르트",
        "url": "/music/mozart-turkish-march.mp3",
        "duration": 229.282
      },
      {
        "title": "교향곡 5번 - 1악장 운명",
        "composer": "베토벤",
        "url": "/music/beethoven-symphony5-1.mp3",
        "duration": 500.088
      },
      {
        "title": "에그몬트 서곡",
        "composer": "베토벤",
        "url": "/music/beethoven-egmont-overture.mp3",
        "duration": 540.876
      },
      {
        "title": "세빌리아의 이발사 서곡",
        "composer": "로시니",
        "url": "/music/rossini-barber-seville-overture.mp3",
        "duration": 439.05
      },
      {
        "title": "헝가리 무곡 5번",
        "composer": "브람스",
        "url": "/music/brahms-hungarian-dance-5.mp3",
        "duration": 172.493
      },
      {
        "title": "꽃의 왈츠 (호두까기 인형)",
        "composer": "차이콥스키",
        "url": "/music/tchaikovsky-waltz-of-flowers.mp3",
        "duration": 394.429
      },
      {
        "title": "현을 위한 세레나데 - 왈츠",
        "composer": "차이콥스키",
        "url": "/music/tchaikovsky-serenade-waltz.mp3",
        "duration": 243.019
      },
      {
        "title": "산왕의 궁전에서 (페르 귄트)",
        "composer": "그리그",
        "url": "/music/grieg-hall-mountain-king.mp3",
        "duration": 152.389
      }
    ]
  },
  {
    "id": "jazz",
    "name": "재즈",
    "emoji": "🎷",
    "tracks": [
      {
        "title": "Beautiful Dream",
        "composer": "Diego Nava",
        "url": "/music/beautiful-dream.mp3",
        "duration": 96.047
      },
      {
        "title": "Latin Lovers",
        "composer": "Ahjay Stelino",
        "url": "/music/latin-lovers.mp3",
        "duration": 94.046
      },
      {
        "title": "Romantic 01",
        "composer": "Lily J",
        "url": "/music/romantic-01.mp3",
        "duration": 98.479
      },
      {
        "title": "Romantic Vacation",
        "composer": "Ahjay Stelino",
        "url": "/music/romantic-vacation.mp3",
        "duration": 111.589
      },
      {
        "title": "Smooth Like Jazz",
        "composer": "Ahjay Stelino",
        "url": "/music/smooth-like-jazz.mp3",
        "duration": 154.509
      },
      {
        "title": "Chill Bro",
        "composer": "Diego Nava",
        "url": "/music/chill-bro.mp3",
        "duration": 98.347
      },
      {
        "title": "Lounging By Moonlight",
        "composer": "Ahjay Stelino",
        "url": "/music/lounging-by-moonlight.mp3",
        "duration": 93.383
      },
      {
        "title": "Soul Jazz",
        "composer": "Francisco Alvear",
        "url": "/music/soul-jazz.mp3",
        "duration": 132.976
      },
      {
        "title": "Lonely in the Bar",
        "composer": "Diego Nava",
        "url": "/music/lonely-in-the-bar.mp3",
        "duration": 91.855
      },
      {
        "title": "Winter Wind",
        "composer": "Diego Nava",
        "url": "/music/winter-wind.mp3",
        "duration": 87.151
      },
      {
        "title": "Jazz 1",
        "composer": "Francisco Alvear",
        "url": "/music/jazz-1-track.mp3",
        "duration": 132.233
      },
      {
        "title": "Nostalgic Night",
        "composer": "Michael Ramir C.",
        "url": "/music/nostalgic-night.mp3",
        "duration": 123.484
      },
      {
        "title": "Lo-Fi 03",
        "composer": "Lily J",
        "url": "/music/lo-fi-03.mp3",
        "duration": 113.141
      },
      {
        "title": "Swing is the Answer",
        "composer": "Diego Nava",
        "url": "/music/swing-is-the-answer.mp3",
        "duration": 106.034
      },
      {
        "title": "Where Are My Boots",
        "composer": "Michael Ramir C.",
        "url": "/music/where-are-my-boots.mp3",
        "duration": 158.899
      },
      {
        "title": "Lost in a Dream",
        "composer": "Michael Ramir C.",
        "url": "/music/lost-in-a-dream.mp3",
        "duration": 108.372
      },
      {
        "title": "Papa",
        "composer": "Michael Ramir C.",
        "url": "/music/papa.mp3",
        "duration": 96.598
      },
      {
        "title": "You Got Jazz",
        "composer": "Diego Nava",
        "url": "/music/you-got-jazz.mp3",
        "duration": 97.997
      },
      {
        "title": "Pop 03",
        "composer": "Grigoriy Nuzhny",
        "url": "/music/pop-03.mp3",
        "duration": 168.406
      },
      {
        "title": "Upbeat Jazz",
        "composer": "Francisco Alvear",
        "url": "/music/upbeat-jazz.mp3",
        "duration": 108.035
      },
      {
        "title": "Fun Jazz",
        "composer": "Francisco Alvear",
        "url": "/music/fun-jazz.mp3",
        "duration": 137.58
      },
      {
        "title": "Slow Walk",
        "composer": "Michael Ramir C.",
        "url": "/music/slow-walk.mp3",
        "duration": 102.114
      },
      {
        "title": "Feeling Good",
        "composer": "Diego Nava",
        "url": "/music/feeling-good.mp3",
        "duration": 99.506
      },
      {
        "title": "Groovy Jazz",
        "composer": "Francisco Alvear",
        "url": "/music/groovy-jazz.mp3",
        "duration": 132.189
      },
      {
        "title": "Close the Lights",
        "composer": "Michael Ramir C.",
        "url": "/music/close-the-lights.mp3",
        "duration": 112.351
      },
      {
        "title": "Space Bird",
        "composer": "Diego Nava",
        "url": "/music/space-bird.mp3",
        "duration": 109.036
      },
      {
        "title": "Funk Jazz",
        "composer": "Francisco Alvear",
        "url": "/music/funk-jazz.mp3",
        "duration": 135.211
      },
      {
        "title": "Romantic 02",
        "composer": "Lily J",
        "url": "/music/romantic-02.mp3",
        "duration": 102.894
      },
      {
        "title": "Lost in Dreams",
        "composer": "Ahjay Stelino",
        "url": "/music/lost-in-dreams.mp3",
        "duration": 123.407
      },
      {
        "title": "Red Moon",
        "composer": "Diego Nava",
        "url": "/music/red-moon.mp3",
        "duration": 103.539
      },
      {
        "title": "Majestic",
        "composer": "Diego Nava",
        "url": "/music/majestic.mp3",
        "duration": 108.627
      },
      {
        "title": "Im Hungry",
        "composer": "Michael Ramir C.",
        "url": "/music/im-hungry.mp3",
        "duration": 108.131
      },
      {
        "title": "Yo Chucky",
        "composer": "Michael Ramir C.",
        "url": "/music/yo-chucky.mp3",
        "duration": 95.427
      },
      {
        "title": "Pop 05",
        "composer": "Grigoriy Nuzhny",
        "url": "/music/pop-05.mp3",
        "duration": 150.953
      }
    ]
  }
];
