// AUTO-GENERATED by scripts/build-combined-music.ts — 직접 수정 금지.
// 재생성: npx tsx scripts/build-combined-music.ts
import type { MusicGenre } from "@/types/music";

export const MUSIC_GENRES: MusicGenre[] = [
  {
    "id": "piano",
    "name": "피아노",
    "emoji": "🎹",
    "durationSeconds": 8280.241,
    "parts": [
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/piano-1.mp3",
        "start": 0,
        "duration": 1352.49
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/piano-2.mp3",
        "start": 1352.49,
        "duration": 1169.345
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/piano-3.mp3",
        "start": 2521.835,
        "duration": 1390.132
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/piano-4.mp3",
        "start": 3911.967,
        "duration": 1362.442
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/piano-5.mp3",
        "start": 5274.41,
        "duration": 1415.941
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/piano-6.mp3",
        "start": 6690.351,
        "duration": 1324.486
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/piano-7.mp3",
        "start": 8014.837,
        "duration": 265.404
      }
    ],
    "cues": [
      {
        "title": "골드베르크 변주곡 - Aria",
        "composer": "바흐",
        "start": 0,
        "duration": 287.19
      },
      {
        "title": "골드베르크 변주곡 - Var.25",
        "composer": "바흐",
        "start": 287.19,
        "duration": 410.54
      },
      {
        "title": "평균율 1권 프렐류드 C장조 BWV 846",
        "composer": "바흐",
        "start": 697.731,
        "duration": 309.708
      },
      {
        "title": "프랑스 모음곡 5번 - 사라방드",
        "composer": "바흐",
        "start": 1007.438,
        "duration": 226.325
      },
      {
        "title": "인벤션 1번 C장조",
        "composer": "바흐",
        "start": 1233.763,
        "duration": 64.104
      },
      {
        "title": "인벤션 8번 F장조",
        "composer": "바흐",
        "start": 1297.868,
        "duration": 54.622
      },
      {
        "title": "소나타 K.380",
        "composer": "스카를라티",
        "start": 1352.49,
        "duration": 327.497
      },
      {
        "title": "월광 소나타 - 1악장",
        "composer": "베토벤",
        "start": 1679.987,
        "duration": 320.104
      },
      {
        "title": "비창 소나타 - 2악장 Adagio",
        "composer": "베토벤",
        "start": 2000.091,
        "duration": 325.46
      },
      {
        "title": "소나타 K.545 - 2악장 Andante",
        "composer": "모차르트",
        "start": 2325.551,
        "duration": 196.284
      },
      {
        "title": "소나타 D.664 - 1악장",
        "composer": "슈베르트",
        "start": 2521.835,
        "duration": 464.327
      },
      {
        "title": "소나타 D.664 - 2악장",
        "composer": "슈베르트",
        "start": 2986.162,
        "duration": 289.228
      },
      {
        "title": "녹턴 Op.9 No.2",
        "composer": "쇼팽",
        "start": 3275.389,
        "duration": 269.976
      },
      {
        "title": "녹턴 Op.27 No.2",
        "composer": "쇼팽",
        "start": 3545.365,
        "duration": 366.602
      },
      {
        "title": "녹턴 Op.15 No.2",
        "composer": "쇼팽",
        "start": 3911.967,
        "duration": 127.713
      },
      {
        "title": "녹턴 Op.55 No.1",
        "composer": "쇼팽",
        "start": 4039.68,
        "duration": 211.017
      },
      {
        "title": "녹턴 Op.48 No.1",
        "composer": "쇼팽",
        "start": 4250.697,
        "duration": 184.189
      },
      {
        "title": "발라드 1번 Op.23",
        "composer": "쇼팽",
        "start": 4434.886,
        "duration": 611.683
      },
      {
        "title": "왈츠 Op.64 No.2",
        "composer": "쇼팽",
        "start": 5046.57,
        "duration": 227.84
      },
      {
        "title": "프렐류드 Op.28 No.4",
        "composer": "쇼팽",
        "start": 5274.41,
        "duration": 144.013
      },
      {
        "title": "프렐류드 Op.28 No.15 \"빗방울\"",
        "composer": "쇼팽",
        "start": 5418.423,
        "duration": 291.788
      },
      {
        "title": "아베 마리아",
        "composer": "슈베르트",
        "start": 5710.21,
        "duration": 249.548
      },
      {
        "title": "즉흥곡 Op.90 No.3",
        "composer": "슈베르트",
        "start": 5959.758,
        "duration": 403.2
      },
      {
        "title": "트로이메라이 (꿈)",
        "composer": "슈만",
        "start": 6362.958,
        "duration": 152.895
      },
      {
        "title": "꿈 후에 (Après un rêve)",
        "composer": "포레",
        "start": 6515.853,
        "duration": 174.498
      },
      {
        "title": "위안 3번",
        "composer": "리스트",
        "start": 6690.351,
        "duration": 283.167
      },
      {
        "title": "아라베스크 1번",
        "composer": "드뷔시",
        "start": 6973.518,
        "duration": 465.058
      },
      {
        "title": "달빛 (베르가마스크 모음곡)",
        "composer": "드뷔시",
        "start": 7438.576,
        "duration": 363.964
      },
      {
        "title": "짐노페디 1번",
        "composer": "사티",
        "start": 7802.54,
        "duration": 212.297
      },
      {
        "title": "뇨시엔느 1번",
        "composer": "사티",
        "start": 8014.837,
        "duration": 265.404
      }
    ]
  },
  {
    "id": "classic",
    "name": "클래식",
    "emoji": "🎻",
    "durationSeconds": 9119.477,
    "parts": [
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/classic-1.mp3",
        "start": 0,
        "duration": 1099.572
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/classic-2.mp3",
        "start": 1099.572,
        "duration": 1061.93
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/classic-3.mp3",
        "start": 2161.502,
        "duration": 1078.857
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/classic-4.mp3",
        "start": 3240.359,
        "duration": 1315.004
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/classic-5.mp3",
        "start": 4555.363,
        "duration": 1414.844
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/classic-6.mp3",
        "start": 5970.207,
        "duration": 1420.199
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/classic-7.mp3",
        "start": 7390.406,
        "duration": 1384.699
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/classic-8.mp3",
        "start": 8775.105,
        "duration": 344.372
      }
    ],
    "cues": [
      {
        "title": "무반주 첼로 모음곡 1번 - 프렐류드",
        "composer": "바흐",
        "start": 0,
        "duration": 146.521
      },
      {
        "title": "캐논 D장조",
        "composer": "파헬벨",
        "start": 146.521,
        "duration": 457.979
      },
      {
        "title": "양은 풀을 뜯고 (BWV 208)",
        "composer": "바흐",
        "start": 604.5,
        "duration": 290.534
      },
      {
        "title": "예수, 인간 소망의 기쁨",
        "composer": "바흐",
        "start": 895.033,
        "duration": 204.539
      },
      {
        "title": "아다지오 G단조",
        "composer": "알비노니",
        "start": 1099.572,
        "duration": 703.922
      },
      {
        "title": "라르고 (옴브라 마이 푸)",
        "composer": "헨델",
        "start": 1803.494,
        "duration": 212.663
      },
      {
        "title": "수상음악 - 에어",
        "composer": "헨델",
        "start": 2016.157,
        "duration": 145.345
      },
      {
        "title": "무반주 플루트 환상곡 1번",
        "composer": "텔레만",
        "start": 2161.502,
        "duration": 462.838
      },
      {
        "title": "정령들의 춤",
        "composer": "글루크",
        "start": 2624.339,
        "duration": 382.851
      },
      {
        "title": "세레나데 (현악 사중주 Op.3-5)",
        "composer": "하이든",
        "start": 3007.19,
        "duration": 233.169
      },
      {
        "title": "아이네 클라이네 - 2악장 Romance",
        "composer": "모차르트",
        "start": 3240.359,
        "duration": 364.513
      },
      {
        "title": "교향곡 40번 - 2악장 Andante",
        "composer": "모차르트",
        "start": 3604.872,
        "duration": 454.844
      },
      {
        "title": "피아노 협주곡 21번 - 2악장 Andante",
        "composer": "모차르트",
        "start": 4059.716,
        "duration": 495.647
      },
      {
        "title": "교향곡 3번 에로이카 - 2악장",
        "composer": "베토벤",
        "start": 4555.363,
        "duration": 925.205
      },
      {
        "title": "교향곡 7번 - 2악장 Allegretto",
        "composer": "베토벤",
        "start": 5480.568,
        "duration": 489.639
      },
      {
        "title": "현악 사중주 2번 - 녹턴",
        "composer": "보로딘",
        "start": 5970.207,
        "duration": 546.612
      },
      {
        "title": "아메리칸 사중주 - Lento",
        "composer": "드보르작",
        "start": 6516.819,
        "duration": 469.185
      },
      {
        "title": "명상곡",
        "composer": "수크",
        "start": 6986.005,
        "duration": 404.402
      },
      {
        "title": "페르 귄트 - 아침 기분",
        "composer": "그리그",
        "start": 7390.406,
        "duration": 227.553
      },
      {
        "title": "페르 귄트 - 오세의 죽음",
        "composer": "그리그",
        "start": 7617.959,
        "duration": 268.983
      },
      {
        "title": "타이스의 명상곡",
        "composer": "마스네",
        "start": 7886.942,
        "duration": 255.843
      },
      {
        "title": "백조 (동물의 사육제)",
        "composer": "생상스",
        "start": 8142.785,
        "duration": 204.8
      },
      {
        "title": "파반",
        "composer": "포레",
        "start": 8347.585,
        "duration": 427.52
      },
      {
        "title": "보칼리제",
        "composer": "라흐마니노프",
        "start": 8775.105,
        "duration": 344.372
      }
    ]
  },
  {
    "id": "energetic",
    "name": "활기찬 클래식",
    "emoji": "🎺",
    "durationSeconds": 4918.726,
    "parts": [
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/energetic-1.mp3",
        "start": 0,
        "duration": 1416.568
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/energetic-2.mp3",
        "start": 1416.568,
        "duration": 1056.862
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/energetic-3.mp3",
        "start": 2473.43,
        "duration": 1041.032
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/energetic-4.mp3",
        "start": 3514.462,
        "duration": 1404.264
      }
    ],
    "cues": [
      {
        "title": "브란덴부르크 협주곡 3번 - 1악장",
        "composer": "바흐",
        "start": 0,
        "duration": 335.621
      },
      {
        "title": "토카타와 푸가 D단조",
        "composer": "바흐",
        "start": 335.621,
        "duration": 520.62
      },
      {
        "title": "수상음악 - 알라 호른파이프",
        "composer": "헨델",
        "start": 856.242,
        "duration": 216.451
      },
      {
        "title": "아이네 클라이네 나흐트무지크 - 1악장 Allegro",
        "composer": "모차르트",
        "start": 1072.692,
        "duration": 343.876
      },
      {
        "title": "교향곡 40번 - 1악장 Molto Allegro",
        "composer": "모차르트",
        "start": 1416.568,
        "duration": 358.4
      },
      {
        "title": "교향곡 25번 - 1악장",
        "composer": "모차르트",
        "start": 1774.968,
        "duration": 469.133
      },
      {
        "title": "터키 행진곡",
        "composer": "모차르트",
        "start": 2244.101,
        "duration": 229.329
      },
      {
        "title": "교향곡 5번 - 1악장 운명",
        "composer": "베토벤",
        "start": 2473.43,
        "duration": 500.114
      },
      {
        "title": "에그몬트 서곡",
        "composer": "베토벤",
        "start": 2973.544,
        "duration": 540.918
      },
      {
        "title": "세빌리아의 이발사 서곡",
        "composer": "로시니",
        "start": 3514.462,
        "duration": 439.092
      },
      {
        "title": "헝가리 무곡 5번",
        "composer": "브람스",
        "start": 3953.554,
        "duration": 172.539
      },
      {
        "title": "꽃의 왈츠 (호두까기 인형)",
        "composer": "차이콥스키",
        "start": 4126.093,
        "duration": 394.475
      },
      {
        "title": "현을 위한 세레나데 - 왈츠",
        "composer": "차이콥스키",
        "start": 4520.568,
        "duration": 243.069
      },
      {
        "title": "산왕의 궁전에서 (페르 귄트)",
        "composer": "그리그",
        "start": 4763.637,
        "duration": 155.089
      }
    ]
  },
  {
    "id": "jazz",
    "name": "재즈",
    "emoji": "🎷",
    "durationSeconds": 4026.148,
    "parts": [
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/jazz-1.mp3",
        "start": 0,
        "duration": 1427.775
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/jazz-2.mp3",
        "start": 1427.775,
        "duration": 1448.385
      },
      {
        "url": "https://amqywfemuxghcosexqct.supabase.co/storage/v1/object/public/jazz-music/v2/jazz-3.mp3",
        "start": 2876.16,
        "duration": 1149.988
      }
    ],
    "cues": [
      {
        "title": "Beautiful Dream",
        "composer": "Diego Nava",
        "start": 0,
        "duration": 96.078
      },
      {
        "title": "Latin Lovers",
        "composer": "Ahjay Stelino",
        "start": 96.078,
        "duration": 94.093
      },
      {
        "title": "Romantic 01",
        "composer": "Lily J",
        "start": 190.171,
        "duration": 98.508
      },
      {
        "title": "Romantic Vacation",
        "composer": "Ahjay Stelino",
        "start": 288.679,
        "duration": 111.621
      },
      {
        "title": "Smooth Like Jazz",
        "composer": "Ahjay Stelino",
        "start": 400.3,
        "duration": 154.54
      },
      {
        "title": "Chill Bro",
        "composer": "Diego Nava",
        "start": 554.841,
        "duration": 98.377
      },
      {
        "title": "Lounging By Moonlight",
        "composer": "Ahjay Stelino",
        "start": 653.218,
        "duration": 93.414
      },
      {
        "title": "Soul Jazz",
        "composer": "Francisco Alvear",
        "start": 746.632,
        "duration": 133.016
      },
      {
        "title": "Lonely in the Bar",
        "composer": "Diego Nava",
        "start": 879.647,
        "duration": 91.899
      },
      {
        "title": "Winter Wind",
        "composer": "Diego Nava",
        "start": 971.546,
        "duration": 87.197
      },
      {
        "title": "Jazz 1",
        "composer": "Francisco Alvear",
        "start": 1058.743,
        "duration": 132.31
      },
      {
        "title": "Nostalgic Night",
        "composer": "Michael Ramir C.",
        "start": 1191.053,
        "duration": 123.533
      },
      {
        "title": "Lo-Fi 03",
        "composer": "Lily J",
        "start": 1314.586,
        "duration": 113.189
      },
      {
        "title": "Swing is the Answer",
        "composer": "Diego Nava",
        "start": 1427.775,
        "duration": 106.083
      },
      {
        "title": "Where Are My Boots",
        "composer": "Michael Ramir C.",
        "start": 1533.858,
        "duration": 158.929
      },
      {
        "title": "Lost in a Dream",
        "composer": "Michael Ramir C.",
        "start": 1692.787,
        "duration": 108.408
      },
      {
        "title": "Papa",
        "composer": "Michael Ramir C.",
        "start": 1801.195,
        "duration": 96.627
      },
      {
        "title": "You Got Jazz",
        "composer": "Diego Nava",
        "start": 1897.822,
        "duration": 98.038
      },
      {
        "title": "Pop 03",
        "composer": "Grigoriy Nuzhny",
        "start": 1995.859,
        "duration": 168.438
      },
      {
        "title": "Upbeat Jazz",
        "composer": "Francisco Alvear",
        "start": 2164.297,
        "duration": 108.069
      },
      {
        "title": "Fun Jazz",
        "composer": "Francisco Alvear",
        "start": 2272.366,
        "duration": 137.613
      },
      {
        "title": "Slow Walk",
        "composer": "Michael Ramir C.",
        "start": 2409.979,
        "duration": 102.165
      },
      {
        "title": "Feeling Good",
        "composer": "Diego Nava",
        "start": 2512.143,
        "duration": 99.553
      },
      {
        "title": "Groovy Jazz",
        "composer": "Francisco Alvear",
        "start": 2611.696,
        "duration": 132.232
      },
      {
        "title": "Dreamy Jazz",
        "composer": "Francisco Alvear",
        "start": 2743.928,
        "duration": 132.232
      },
      {
        "title": "Close the Lights",
        "composer": "Michael Ramir C.",
        "start": 2876.16,
        "duration": 112.379
      },
      {
        "title": "Space Bird",
        "composer": "Diego Nava",
        "start": 2988.538,
        "duration": 109.087
      },
      {
        "title": "Funk Jazz",
        "composer": "Francisco Alvear",
        "start": 3097.626,
        "duration": 135.262
      },
      {
        "title": "Romantic 02",
        "composer": "Lily J",
        "start": 3232.888,
        "duration": 102.922
      },
      {
        "title": "Lost in Dreams",
        "composer": "Ahjay Stelino",
        "start": 3335.81,
        "duration": 123.455
      },
      {
        "title": "Red Moon",
        "composer": "Diego Nava",
        "start": 3459.265,
        "duration": 103.576
      },
      {
        "title": "Majestic",
        "composer": "Diego Nava",
        "start": 3562.84,
        "duration": 108.669
      },
      {
        "title": "Im Hungry",
        "composer": "Michael Ramir C.",
        "start": 3671.51,
        "duration": 108.173
      },
      {
        "title": "Yo Chucky",
        "composer": "Michael Ramir C.",
        "start": 3779.683,
        "duration": 95.478
      },
      {
        "title": "Pop 05",
        "composer": "Grigoriy Nuzhny",
        "start": 3875.16,
        "duration": 150.988
      }
    ]
  }
];
