import type { MusicTrack } from "@/types/music";

/** 전체 트랙 목록 */
export const MUSIC_TRACKS: MusicTrack[] = [
  // ─── 피아노 (25곡) ───
  {
    id: "track-001",
    title: "골드베르크 변주곡 - Aria",
    composer: "바흐",
    performer: "Musopen",
    sourceUrl: "/music/bach-goldberg-aria.mp3",
    isExternal: false,
    durationSeconds: 292,
    moods: ["focus", "peaceful"],
    era: "baroque",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-002",
    title: "골드베르크 변주곡 - Var.25",
    composer: "바흐",
    performer: "Musopen",
    sourceUrl: "/music/bach-goldberg-var25.mp3",
    isExternal: false,
    durationSeconds: 410,
    moods: ["contemplative", "emotional"],
    era: "baroque",
    instruments: ["piano"],
    intensity: 2,
  },
  {
    id: "track-003",
    title: "골드베르크 변주곡 - Aria da Capo",
    composer: "바흐",
    performer: "Musopen",
    sourceUrl: "/music/bach-goldberg-ariadacapo.mp3",
    isExternal: false,
    durationSeconds: 339,
    moods: ["focus", "peaceful"],
    era: "baroque",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-004",
    title: "평균율 1권 프렐류드 C장조 BWV 846",
    composer: "바흐",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Bach_WellTemperedClavier/JohannSebastianBach-PreludeNo.1InCMajorBwv846.mp3",
    isExternal: true,
    durationSeconds: 135,
    moods: ["focus", "bright"],
    era: "baroque",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-005",
    title: "프랑스 모음곡 5번 - 사라방드 BWV 816",
    composer: "바흐",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Bach_FrenchSuites/JohannSebastianBach-FrenchSuiteNo.5InGMajorBwv816-03-Sarabande.mp3",
    isExternal: true,
    durationSeconds: 240,
    moods: ["peaceful", "contemplative"],
    era: "baroque",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-006",
    title: "소나타 16번 K.545 - 2악장 Andante",
    composer: "모차르트",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Mozart_PianoSonatas/WolfgangAmadeusMozart-PianoSonataNo.16InCMajorK545-02-Andante.mp3",
    isExternal: true,
    durationSeconds: 360,
    moods: ["relaxing", "bright"],
    era: "classical",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-007",
    title: "비창 소나타 - 2악장 Adagio",
    composer: "베토벤",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Beethoven_PianoSonatas/LudwigVanBeethoven-PianoSonataNo.8InCMinorOp.13Pathetique-02-AdagioCantabile.mp3",
    isExternal: true,
    durationSeconds: 300,
    moods: ["contemplative", "emotional"],
    era: "classical",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-008",
    title: "월광 소나타 - 1악장",
    composer: "베토벤",
    performer: "Musopen",
    sourceUrl: "/music/beethoven-moonlight-1.mp3",
    isExternal: false,
    durationSeconds: 360,
    moods: ["contemplative", "peaceful"],
    era: "classical",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-009",
    title: "소나타 D.664 - 1악장",
    composer: "슈베르트",
    performer: "Musopen",
    sourceUrl: "/music/schubert-allegro.mp3",
    isExternal: false,
    durationSeconds: 466,
    moods: ["focus", "bright"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 2,
  },
  {
    id: "track-010",
    title: "소나타 D.664 - 2악장",
    composer: "슈베르트",
    performer: "Musopen",
    sourceUrl: "/music/schubert-andante.mp3",
    isExternal: false,
    durationSeconds: 290,
    moods: ["contemplative", "emotional"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-011",
    title: "즉흥곡 Op.90 No.3",
    composer: "슈베르트",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Schubert_Impromptus/FranzSchubert-ImpromptuOp.90No.3InGFlatMajor.mp3",
    isExternal: true,
    durationSeconds: 360,
    moods: ["relaxing", "emotional"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-012",
    title: "녹턴 Op.9 No.2",
    composer: "쇼팽",
    performer: "Musopen",
    sourceUrl: "/music/chopin-nocturne-op9-2.mp3",
    isExternal: false,
    durationSeconds: 270,
    moods: ["relaxing", "emotional"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-013",
    title: "녹턴 Op.27 No.2",
    composer: "쇼팽",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/musopen-chopin/Musopen%20-%20Chopin%20-%20Nocturne%20Op.%2027%20No.%202%20in%20Db%20Major.mp3",
    isExternal: true,
    durationSeconds: 360,
    moods: ["relaxing", "peaceful"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-014",
    title: "발라드 1번 Op.23",
    composer: "쇼팽",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/musopen-chopin/Musopen%20-%20Chopin%20-%20Ballade%20No.%201%20Op.%2023%20in%20G%20Minor.mp3",
    isExternal: true,
    durationSeconds: 540,
    moods: ["emotional", "contemplative"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 3,
  },
  {
    id: "track-015",
    title: "왈츠 Op.64 No.2",
    composer: "쇼팽",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/musopen-chopin/Musopen%20-%20Chopin%20-%20Waltz%20Op.%2064%20No.%202%20in%20C%23%20Minor.mp3",
    isExternal: true,
    durationSeconds: 210,
    moods: ["emotional", "bright"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 2,
  },
  {
    id: "track-016",
    title: "프렐류드 Op.28 No.4",
    composer: "쇼팽",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/musopen-chopin/Musopen%20-%20Chopin%20-%20Prelude%20Op.%2028%20No.%204%20in%20E%20Minor.mp3",
    isExternal: true,
    durationSeconds: 120,
    moods: ["contemplative", "emotional"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-017",
    title: '프렐류드 Op.28 No.15 "빗방울"',
    composer: "쇼팽",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/musopen-chopin/Musopen%20-%20Chopin%20-%20Prelude%20Op.%2028%20No.%2015%20in%20Db%20Major.mp3",
    isExternal: true,
    durationSeconds: 330,
    moods: ["contemplative", "peaceful"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 2,
  },
  {
    id: "track-018",
    title: "인터메초 Op.118 No.2",
    composer: "브람스",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Brahms_PianoWorks/JohannesBrahms-IntermezzoOp.118No.2InAMajor.mp3",
    isExternal: true,
    durationSeconds: 360,
    moods: ["contemplative", "relaxing"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-019",
    title: "아라베스크 1번",
    composer: "드뷔시",
    performer: "Musopen",
    sourceUrl: "/music/debussy-arabesque-1.mp3",
    isExternal: false,
    durationSeconds: 300,
    moods: ["bright", "relaxing"],
    era: "impressionist",
    instruments: ["piano"],
    intensity: 2,
  },
  {
    id: "track-020",
    title: "달빛 (베르가마스크 모음곡)",
    composer: "드뷔시",
    performer: "Musopen",
    sourceUrl: "/music/debussy-clair-de-lune.mp3",
    isExternal: false,
    durationSeconds: 300,
    moods: ["peaceful", "contemplative"],
    era: "impressionist",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-021",
    title: "짐노페디 1번",
    composer: "사티",
    performer: "Musopen",
    sourceUrl: "/music/satie-gymnopedie-1.mp3",
    isExternal: false,
    durationSeconds: 195,
    moods: ["peaceful", "contemplative"],
    era: "impressionist",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-022",
    title: "그노시엔느 1번",
    composer: "사티",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/Erik_Satie_-_Gnossienne_No._1/Erik_Satie_-_Gnossienne_No._1.mp3",
    isExternal: true,
    durationSeconds: 240,
    moods: ["contemplative", "peaceful"],
    era: "impressionist",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-023",
    title: "트로이메라이 (어린이의 정경)",
    composer: "슈만",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Schumann_Kinderszenen/RobertSchumann-KinderszenenOp.15-07-Traumerei.mp3",
    isExternal: true,
    durationSeconds: 180,
    moods: ["peaceful", "emotional"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-024",
    title: "사랑의 꿈 3번",
    composer: "리스트",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Liszt_Liebestraume/FranzLiszt-LiebestraumNo.3InAbMajor.mp3",
    isExternal: true,
    durationSeconds: 300,
    moods: ["emotional", "relaxing"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 2,
  },
  {
    id: "track-025",
    title: "베네치아 곤돌라의 노래 Op.30 No.6",
    composer: "멘델스존",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Mendelssohn_SongsWithoutWords/FelixMendelssohn-SongsWithoutWordsOp.30-No.6VenetianGondolasSong.mp3",
    isExternal: true,
    durationSeconds: 180,
    moods: ["relaxing", "emotional"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 1,
  },

  // ─── 현악/실내악 (20곡) ───
  {
    id: "track-026",
    title: "무반주 첼로 모음곡 1번 - 프렐류드",
    composer: "바흐",
    performer: "Musopen",
    sourceUrl: "/music/bach-cello-suite-1-prelude.mp3",
    isExternal: false,
    durationSeconds: 165,
    moods: ["focus", "bright"],
    era: "baroque",
    instruments: ["cello"],
    intensity: 2,
  },
  {
    id: "track-027",
    title: "G선상의 아리아",
    composer: "바흐",
    performer: "Musopen",
    sourceUrl: "/music/bach-air-on-g-string.mp3",
    isExternal: false,
    durationSeconds: 300,
    moods: ["peaceful", "relaxing"],
    era: "baroque",
    instruments: ["strings"],
    intensity: 1,
  },
  {
    id: "track-028",
    title: "현악 사중주 2번 - 녹턴",
    composer: "보로딘",
    performer: "Musopen",
    sourceUrl: "/music/borodin-nocturne.mp3",
    isExternal: false,
    durationSeconds: 547,
    moods: ["relaxing", "emotional"],
    era: "romantic",
    instruments: ["string_quartet"],
    intensity: 1,
  },
  {
    id: "track-029",
    title: "아메리칸 사중주 - Lento",
    composer: "드보르작",
    performer: "Musopen",
    sourceUrl: "/music/dvorak-lento.mp3",
    isExternal: false,
    durationSeconds: 471,
    moods: ["relaxing", "peaceful"],
    era: "romantic",
    instruments: ["string_quartet"],
    intensity: 1,
  },
  {
    id: "track-030",
    title: "명상곡",
    composer: "수크",
    performer: "Musopen",
    sourceUrl: "/music/suk-meditation.mp3",
    isExternal: false,
    durationSeconds: 405,
    moods: ["contemplative", "emotional"],
    era: "romantic",
    instruments: ["strings"],
    intensity: 1,
  },
  {
    id: "track-031",
    title: "캐논 D장조",
    composer: "파헬벨",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Pachelbel_Canon/JohannPachelbel-CanonInDMajor.mp3",
    isExternal: true,
    durationSeconds: 300,
    moods: ["relaxing", "peaceful"],
    era: "baroque",
    instruments: ["strings"],
    intensity: 1,
  },
  {
    id: "track-032",
    title: "아다지오 G단조",
    composer: "알비노니",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Albinoni_Adagio/TommasoAlbinoni-AdagioInGMinor.mp3",
    isExternal: true,
    durationSeconds: 480,
    moods: ["contemplative", "emotional"],
    era: "baroque",
    instruments: ["strings", "orchestra"],
    intensity: 1,
  },
  {
    id: "track-033",
    title: "현악 세레나데 - 2악장 Waltz",
    composer: "차이콥스키",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Tchaikovsky_SerenadeForStrings/PyotrIlyichTchaikovsky-SerenadeForStringsInCMajorOp.48-02-WaltzModeratoTempodiValse.mp3",
    isExternal: true,
    durationSeconds: 240,
    moods: ["bright", "relaxing"],
    era: "romantic",
    instruments: ["strings"],
    intensity: 2,
  },
  {
    id: "track-034",
    title: "현악 세레나데 - 3악장 Elegy",
    composer: "차이콥스키",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Tchaikovsky_SerenadeForStrings/PyotrIlyichTchaikovsky-SerenadeForStringsInCMajorOp.48-03-ElegiaLarghettoElegiaco.mp3",
    isExternal: true,
    durationSeconds: 480,
    moods: ["contemplative", "emotional"],
    era: "romantic",
    instruments: ["strings"],
    intensity: 2,
  },
  {
    id: "track-035",
    title: "홀베르크 모음곡 - 사라방드",
    composer: "그리그",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Grieg_HolbergSuite/EdvardGrieg-HolbergSuiteOp.40-03-Sarabande.mp3",
    isExternal: true,
    durationSeconds: 300,
    moods: ["contemplative", "peaceful"],
    era: "romantic",
    instruments: ["strings"],
    intensity: 1,
  },
  {
    id: "track-036",
    title: "홀베르크 모음곡 - Air",
    composer: "그리그",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Grieg_HolbergSuite/EdvardGrieg-HolbergSuiteOp.40-04-Air.mp3",
    isExternal: true,
    durationSeconds: 300,
    moods: ["relaxing", "emotional"],
    era: "romantic",
    instruments: ["strings"],
    intensity: 1,
  },
  {
    id: "track-037",
    title: "수상 음악 - Air",
    composer: "헨델",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Handel_WaterMusic/GeorgeFriedrichHandel-WaterMusic-Air.mp3",
    isExternal: true,
    durationSeconds: 240,
    moods: ["bright", "relaxing"],
    era: "baroque",
    instruments: ["orchestra"],
    intensity: 2,
  },
  {
    id: "track-038",
    title: "현악 5중주 D.956 - 2악장 Adagio",
    composer: "슈베르트",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Schubert_StringQuintet/FranzSchubert-StringQuintetInCMajorD956-02-Adagio.mp3",
    isExternal: true,
    durationSeconds: 780,
    moods: ["contemplative", "emotional"],
    era: "romantic",
    instruments: ["strings"],
    intensity: 1,
  },
  {
    id: "track-039",
    title: "현악 사중주 6번 Op.18 - 2악장 Adagio",
    composer: "베토벤",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Beethoven_StringQuartetNo.6inBFlatMajorOp.18/LudwigVanBeethoven-StringQuartetNo.6InBFlatMajorOp.18No.6-02-AdagioManonTroppo.mp3",
    isExternal: true,
    durationSeconds: 420,
    moods: ["contemplative", "peaceful"],
    era: "classical",
    instruments: ["string_quartet"],
    intensity: 1,
  },
  {
    id: "track-040",
    title: "백조 (동물의 사육제)",
    composer: "생상스",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/SaintSaens_CarnivalOfTheAnimals/CamilleSaintSaens-CarnivalOfTheAnimals-13-TheSwan.mp3",
    isExternal: true,
    durationSeconds: 180,
    moods: ["peaceful", "emotional"],
    era: "romantic",
    instruments: ["cello", "strings"],
    intensity: 1,
  },
  {
    id: "track-041",
    title: "타이스의 명상곡",
    composer: "마스네",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Massenet_ThaisMeditation/JulesMassenet-MeditationFromThais.mp3",
    isExternal: true,
    durationSeconds: 300,
    moods: ["emotional", "contemplative"],
    era: "romantic",
    instruments: ["strings", "orchestra"],
    intensity: 2,
  },
  {
    id: "track-042",
    title: "보칼리즈 Op.34 No.14",
    composer: "라흐마니노프",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Rachmaninoff_Vocalise/SergeiRachmaninoff-VocaliseOp.34No.14.mp3",
    isExternal: true,
    durationSeconds: 360,
    moods: ["emotional", "contemplative"],
    era: "romantic",
    instruments: ["strings", "orchestra"],
    intensity: 2,
  },
  {
    id: "track-043",
    title: "현악 8중주 Op.20 - 3악장 Andante",
    composer: "멘델스존",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Mendelssohn_StringOctet/FelixMendelssohn-StringOctetInEFlatMajorOp.20-03-AndanteScherzando.mp3",
    isExternal: true,
    durationSeconds: 360,
    moods: ["relaxing", "bright"],
    era: "romantic",
    instruments: ["strings"],
    intensity: 2,
  },
  {
    id: "track-044",
    title: "세레나데 사중주 Op.3 No.5 - 2악장",
    composer: "하이든",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Haydn_StringQuartets/JosephHaydn-StringQuartetOp.3No.5-02-AndanteCantabile.mp3",
    isExternal: true,
    durationSeconds: 300,
    moods: ["relaxing", "bright"],
    era: "classical",
    instruments: ["string_quartet"],
    intensity: 1,
  },
  {
    id: "track-045",
    title: "쇼팽 - 녹턴 Op.48 No.1",
    composer: "쇼팽",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/musopen-chopin/Musopen%20-%20Chopin%20-%20Nocturne%20Op.%2048%20No.%201%20in%20C%20Minor.mp3",
    isExternal: true,
    durationSeconds: 360,
    moods: ["contemplative", "emotional"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 2,
  },

  // ─── 오케스트라 (15곡) ───
  {
    id: "track-046",
    title: "페르 귄트 - 아침 기분",
    composer: "그리그",
    performer: "Musopen",
    sourceUrl: "/music/grieg-morning-mood.mp3",
    isExternal: false,
    durationSeconds: 229,
    moods: ["bright", "peaceful"],
    era: "romantic",
    instruments: ["orchestra"],
    intensity: 2,
  },
  {
    id: "track-047",
    title: "페르 귄트 - 오세의 죽음",
    composer: "그리그",
    performer: "Musopen",
    sourceUrl: "/music/grieg-aases-death.mp3",
    isExternal: false,
    durationSeconds: 273,
    moods: ["contemplative", "emotional"],
    era: "romantic",
    instruments: ["strings"],
    intensity: 2,
  },
  {
    id: "track-048",
    title: "디베르티멘토 K.136 - 2악장 Andante",
    composer: "모차르트",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Mozart_Divertimento/WolfgangAmadeusMozart-DivertimentoInDMajorK136-02-Andante.mp3",
    isExternal: true,
    durationSeconds: 360,
    moods: ["relaxing", "bright"],
    era: "classical",
    instruments: ["strings"],
    intensity: 1,
  },
  {
    id: "track-049",
    title: "아이네 클라이네 - 2악장 Romance",
    composer: "모차르트",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Mozart_EineKleineNachtmusik/WolfgangAmadeusMozart-EineKleineNachtmusikK525-02-Romanze.mp3",
    isExternal: true,
    durationSeconds: 360,
    moods: ["relaxing", "peaceful"],
    era: "classical",
    instruments: ["strings"],
    intensity: 1,
  },
  {
    id: "track-050",
    title: '교향곡 6번 "전원" - 2악장',
    composer: "베토벤",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Beethoven_Symphony6/LudwigVanBeethoven-SymphonyNo.6InFMajorOp.68Pastoral-02-AndanteMoltoMossoSceneByTheBrook.mp3",
    isExternal: true,
    durationSeconds: 720,
    moods: ["relaxing", "peaceful"],
    era: "classical",
    instruments: ["orchestra"],
    intensity: 1,
  },
  {
    id: "track-051",
    title: "교향곡 3번 - 3악장",
    composer: "브람스",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Brahms_Symphony3/JohannesBrahms-SymphonyNo.3InFMajorOp.90-03-PocoAllegretto.mp3",
    isExternal: true,
    durationSeconds: 360,
    moods: ["emotional", "contemplative"],
    era: "romantic",
    instruments: ["orchestra"],
    intensity: 2,
  },
  {
    id: "track-052",
    title: "호두까기 인형 - 꽃의 왈츠",
    composer: "차이콥스키",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Tchaikovsky_Nutcracker/PyotrIlyichTchaikovsky-TheNutcrackerOp.71-WaltzOfTheFlowers.mp3",
    isExternal: true,
    durationSeconds: 420,
    moods: ["bright", "relaxing"],
    era: "romantic",
    instruments: ["orchestra"],
    intensity: 3,
  },
  {
    id: "track-053",
    title: "수족관 (동물의 사육제)",
    composer: "생상스",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/SaintSaens_CarnivalOfTheAnimals/CamilleSaintSaens-CarnivalOfTheAnimals-07-Aquarium.mp3",
    isExternal: true,
    durationSeconds: 135,
    moods: ["peaceful", "contemplative"],
    era: "romantic",
    instruments: ["orchestra"],
    intensity: 1,
  },
  {
    id: "track-054",
    title: '칸타타 BWV 147 "주여 인간 소망의 기쁨이여"',
    composer: "바흐",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Bach_JesuJoyOfMansDesiring/JohannSebastianBach-JesuJoyOfMansDesiring.mp3",
    isExternal: true,
    durationSeconds: 240,
    moods: ["peaceful", "bright"],
    era: "baroque",
    instruments: ["orchestra"],
    intensity: 1,
  },
  {
    id: "track-055",
    title: "사계 - 봄 2악장 Largo",
    composer: "비발디",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Vivaldi_FourSeasons/AntonioVivaldi-TheFourSeasons-Spring-02-Largo.mp3",
    isExternal: true,
    durationSeconds: 165,
    moods: ["peaceful", "relaxing"],
    era: "baroque",
    instruments: ["strings"],
    intensity: 1,
  },
  {
    id: "track-056",
    title: "교향곡 40번 - 2악장 Andante",
    composer: "모차르트",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Mozart_SymphonyNo.40inGMinor/WolfgangAmadeusMozart-SymphonyNo.40InGMinorK.550-02-Andante.mp3",
    isExternal: true,
    durationSeconds: 480,
    moods: ["relaxing", "contemplative"],
    era: "classical",
    instruments: ["orchestra"],
    intensity: 2,
  },
  {
    id: "track-057",
    title: "교향곡 6번 비창 - 2악장",
    composer: "차이콥스키",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Tchaikovsky_Symphony6/PyotrIlyichTchaikovsky-SymphonyNo.6InBMinorOp.74Pathetique-02-AllegroConGrazia.mp3",
    isExternal: true,
    durationSeconds: 480,
    moods: ["bright", "relaxing"],
    era: "romantic",
    instruments: ["orchestra"],
    intensity: 2,
  },
  {
    id: "track-058",
    title: "교향곡 3번 에로이카 - 2악장",
    composer: "베토벤",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Beethoven_SymphonyNo.3Eroica/LudwigVanBeethoven-SymphonyNo.3InEFlatMajorEroicaOp.55-02-MarciaFunebreAdagioAssai.mp3",
    isExternal: true,
    durationSeconds: 960,
    moods: ["contemplative", "emotional"],
    era: "classical",
    instruments: ["orchestra"],
    intensity: 2,
  },
  {
    id: "track-059",
    title: "쇼팽 - 녹턴 Op.55 No.1",
    composer: "쇼팽",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/musopen-chopin/Musopen%20-%20Chopin%20-%20Nocturne%20Op.%2055%20No.%201%20in%20F%20Minor.mp3",
    isExternal: true,
    durationSeconds: 300,
    moods: ["contemplative", "emotional"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 1,
  },
  {
    id: "track-060",
    title: "쇼팽 - 프렐류드 Op.28 No.7",
    composer: "쇼팽",
    performer: "Musopen",
    sourceUrl: "https://archive.org/download/musopen-chopin/Musopen%20-%20Chopin%20-%20Prelude%20Op.%2028%20No.%207%20in%20A%20Major.mp3",
    isExternal: true,
    durationSeconds: 45,
    moods: ["peaceful", "bright"],
    era: "romantic",
    instruments: ["piano"],
    intensity: 1,
  },
];
