import type { MusicTrack } from "@/types/music";

/** 전체 트랙 목록 (검증된 34곡 — 폴백용) */
export const MUSIC_TRACKS: MusicTrack[] = [
  // ─── 로컬 파일 (17곡) ───
  { id: "track-001", title: "골드베르크 변주곡 - Aria", composer: "바흐", performer: "Musopen", sourceUrl: "/music/bach-goldberg-aria.mp3", isExternal: false, durationSeconds: 292, moods: ["focus", "peaceful"], era: "baroque", instruments: ["piano"], intensity: 1 },
  { id: "track-002", title: "골드베르크 변주곡 - Var.25", composer: "바흐", performer: "Musopen", sourceUrl: "/music/bach-goldberg-var25.mp3", isExternal: false, durationSeconds: 410, moods: ["contemplative", "emotional"], era: "baroque", instruments: ["piano"], intensity: 2 },
  { id: "track-003", title: "골드베르크 변주곡 - Aria da Capo", composer: "바흐", performer: "Musopen", sourceUrl: "/music/bach-goldberg-ariadacapo.mp3", isExternal: false, durationSeconds: 339, moods: ["focus", "peaceful"], era: "baroque", instruments: ["piano"], intensity: 1 },
  { id: "track-008", title: "월광 소나타 - 1악장", composer: "베토벤", performer: "Musopen", sourceUrl: "/music/beethoven-moonlight-1.mp3", isExternal: false, durationSeconds: 360, moods: ["contemplative", "peaceful"], era: "classical", instruments: ["piano"], intensity: 1 },
  { id: "track-009", title: "소나타 D.664 - 1악장", composer: "슈베르트", performer: "Musopen", sourceUrl: "/music/schubert-allegro.mp3", isExternal: false, durationSeconds: 466, moods: ["focus", "bright"], era: "romantic", instruments: ["piano"], intensity: 2 },
  { id: "track-010", title: "소나타 D.664 - 2악장", composer: "슈베르트", performer: "Musopen", sourceUrl: "/music/schubert-andante.mp3", isExternal: false, durationSeconds: 290, moods: ["contemplative", "emotional"], era: "romantic", instruments: ["piano"], intensity: 1 },
  { id: "track-012", title: "녹턴 Op.9 No.2", composer: "쇼팽", performer: "Musopen", sourceUrl: "/music/chopin-nocturne-op9-2.mp3", isExternal: false, durationSeconds: 270, moods: ["relaxing", "emotional"], era: "romantic", instruments: ["piano"], intensity: 1 },
  { id: "track-019", title: "아라베스크 1번", composer: "드뷔시", performer: "Musopen", sourceUrl: "/music/debussy-arabesque-1.mp3", isExternal: false, durationSeconds: 300, moods: ["bright", "relaxing"], era: "impressionist", instruments: ["piano"], intensity: 2 },
  { id: "track-020", title: "달빛 (베르가마스크 모음곡)", composer: "드뷔시", performer: "Musopen", sourceUrl: "/music/debussy-clair-de-lune.mp3", isExternal: false, durationSeconds: 300, moods: ["peaceful", "contemplative"], era: "impressionist", instruments: ["piano"], intensity: 1 },
  { id: "track-021", title: "짐노페디 1번", composer: "사티", performer: "Musopen", sourceUrl: "/music/satie-gymnopedie-1.mp3", isExternal: false, durationSeconds: 195, moods: ["peaceful", "contemplative"], era: "impressionist", instruments: ["piano"], intensity: 1 },
  { id: "track-026", title: "무반주 첼로 모음곡 1번 - 프렐류드", composer: "바흐", performer: "Musopen", sourceUrl: "/music/bach-cello-suite-1-prelude.mp3", isExternal: false, durationSeconds: 165, moods: ["focus", "bright"], era: "baroque", instruments: ["cello"], intensity: 2 },
  { id: "track-027", title: "G선상의 아리아", composer: "바흐", performer: "Musopen", sourceUrl: "/music/bach-air-on-g-string.mp3", isExternal: false, durationSeconds: 300, moods: ["peaceful", "relaxing"], era: "baroque", instruments: ["strings"], intensity: 1 },
  { id: "track-028", title: "현악 사중주 2번 - 녹턴", composer: "보로딘", performer: "Musopen", sourceUrl: "/music/borodin-nocturne.mp3", isExternal: false, durationSeconds: 547, moods: ["relaxing", "emotional"], era: "romantic", instruments: ["string_quartet"], intensity: 1 },
  { id: "track-029", title: "아메리칸 사중주 - Lento", composer: "드보르작", performer: "Musopen", sourceUrl: "/music/dvorak-lento.mp3", isExternal: false, durationSeconds: 471, moods: ["relaxing", "peaceful"], era: "romantic", instruments: ["string_quartet"], intensity: 1 },
  { id: "track-030", title: "명상곡", composer: "수크", performer: "Musopen", sourceUrl: "/music/suk-meditation.mp3", isExternal: false, durationSeconds: 405, moods: ["contemplative", "emotional"], era: "romantic", instruments: ["strings"], intensity: 1 },
  { id: "track-046", title: "페르 귄트 - 아침 기분", composer: "그리그", performer: "Musopen", sourceUrl: "/music/grieg-morning-mood.mp3", isExternal: false, durationSeconds: 229, moods: ["bright", "peaceful"], era: "romantic", instruments: ["orchestra"], intensity: 2 },
  { id: "track-047", title: "페르 귄트 - 오세의 죽음", composer: "그리그", performer: "Musopen", sourceUrl: "/music/grieg-aases-death.mp3", isExternal: false, durationSeconds: 273, moods: ["contemplative", "emotional"], era: "romantic", instruments: ["strings"], intensity: 2 },

  // ─── 외부 파일 (17곡, URL 검증 완료) ───
  { id: "track-004", title: "평균율 1권 프렐류드 C장조 BWV 846", composer: "바흐", performer: "Friedrich Gulda", sourceUrl: "https://archive.org/download/prelude-and-fugue-no.-1-in-c-major-bwv-846-from-bachs-well-tempered-clavier-gulda-pianist/Prelude%20and%20Fugue%20No.%201%20in%20C%20major%2C%20BWV%20846%2C%20from%20Bachs%20Well-tempered%20Clavier%2C%20Gulda%20pianist.mp3", isExternal: true, durationSeconds: 135, moods: ["focus", "bright"], era: "baroque", instruments: ["piano"], intensity: 1 },
  { id: "track-013", title: "녹턴 Op.27 No.2", composer: "쇼팽", performer: "Musopen", sourceUrl: "https://archive.org/download/musopen-chopin/NocturneOp27No2.mp3", isExternal: true, durationSeconds: 360, moods: ["relaxing", "peaceful"], era: "romantic", instruments: ["piano"], intensity: 1 },
  { id: "track-014", title: "발라드 1번 Op.23", composer: "쇼팽", performer: "Musopen", sourceUrl: "https://archive.org/download/musopen-chopin/Ballade%20no.%201%20-%20Op.%2023.mp3", isExternal: true, durationSeconds: 540, moods: ["emotional", "contemplative"], era: "romantic", instruments: ["piano"], intensity: 3 },
  { id: "track-015", title: "왈츠 Op.64 No.2", composer: "쇼팽", performer: "Musopen", sourceUrl: "https://archive.org/download/musopen-chopin/Waltz%20Op.%2064%20no.%202%20in%20C%20sharp%20minor.mp3", isExternal: true, durationSeconds: 210, moods: ["emotional", "bright"], era: "romantic", instruments: ["piano"], intensity: 2 },
  { id: "track-016", title: "프렐류드 Op.28 No.4", composer: "쇼팽", performer: "Musopen", sourceUrl: "https://archive.org/download/PeludiumEMollOp.28Nr.4largo/Peludium%20e-moll%20op.28%20nr.4%28largo%29.mp3", isExternal: true, durationSeconds: 120, moods: ["contemplative", "emotional"], era: "romantic", instruments: ["piano"], intensity: 1 },
  { id: "track-017", title: "프렐류드 Op.28 No.15 \"빗방울\"", composer: "쇼팽", performer: "Musopen", sourceUrl: "https://archive.org/download/musopen-chopin/Prelude%20Op.%2028%20no.%2015.mp3", isExternal: true, durationSeconds: 330, moods: ["contemplative", "peaceful"], era: "romantic", instruments: ["piano"], intensity: 2 },
  { id: "track-031", title: "캐논 D장조", composer: "파헬벨", performer: "Public Domain", sourceUrl: "https://archive.org/download/PachelbelsCanoninD/Canon_in_D_Piano.mp3", isExternal: true, durationSeconds: 300, moods: ["relaxing", "peaceful"], era: "baroque", instruments: ["piano"], intensity: 1 },
  { id: "track-049", title: "아이네 클라이네 - 2악장 Romance", composer: "모차르트", performer: "Collegium Aureum", sourceUrl: "https://archive.org/download/mozart-ine-kleine-nachtmusik-vinyl-1978/A2-Romanza%20-%20Andante.mp3", isExternal: true, durationSeconds: 360, moods: ["relaxing", "peaceful"], era: "classical", instruments: ["strings"], intensity: 1 },
  { id: "track-055", title: "사계 - 봄 2악장 Largo", composer: "비발디", performer: "Wichita State University", sourceUrl: "https://archive.org/download/The_Four_Seasons_Vivaldi-10361/John_Harrison_with_the_Wichita_State_University_Chamber_Players_-_02_-_Spring_Mvt_2_Largo.mp3", isExternal: true, durationSeconds: 165, moods: ["peaceful", "relaxing"], era: "baroque", instruments: ["strings"], intensity: 1 },
  { id: "track-056", title: "교향곡 40번 - 2악장 Andante", composer: "모차르트", performer: "Musopen", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Mozart_SymphonyNo.40inGMinor/WolfgangAmadeusMozart-SymphonyNo.40InGMinorK.550-02-Andante.mp3", isExternal: true, durationSeconds: 480, moods: ["relaxing", "contemplative"], era: "classical", instruments: ["orchestra"], intensity: 2 },
  { id: "track-058", title: "교향곡 3번 에로이카 - 2악장", composer: "베토벤", performer: "Musopen", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Beethoven_SymphonyNo.3Eroica/LudwigVanBeethoven-SymphonyNo.3InEFlatMajorEroicaOp.55-02-MarciaFunebreAdagioAssai.mp3", isExternal: true, durationSeconds: 960, moods: ["contemplative", "emotional"], era: "classical", instruments: ["orchestra"], intensity: 2 },
  { id: "track-061", title: "사계 - 봄 1악장 Allegro", composer: "비발디", performer: "Wichita State University", sourceUrl: "https://archive.org/download/The_Four_Seasons_Vivaldi-10361/John_Harrison_with_the_Wichita_State_University_Chamber_Players_-_01_-_Spring_Mvt_1_Allegro.mp3", isExternal: true, durationSeconds: 210, moods: ["energetic", "bright"], era: "baroque", instruments: ["strings"], intensity: 3 },
  { id: "track-062", title: "사계 - 여름 3악장 Presto", composer: "비발디", performer: "Wichita State University", sourceUrl: "https://archive.org/download/The_Four_Seasons_Vivaldi-10361/John_Harrison_with_the_Wichita_State_University_Chamber_Players_-_06_-_Summer_Mvt_3_Presto.mp3", isExternal: true, durationSeconds: 180, moods: ["energetic", "bright"], era: "baroque", instruments: ["strings"], intensity: 3 },
  { id: "track-063", title: "아이네 클라이네 나흐트무지크 - 1악장 Allegro", composer: "모차르트", performer: "Collegium Aureum", sourceUrl: "https://archive.org/download/mozart-ine-kleine-nachtmusik-vinyl-1978/A1-Allegro.mp3", isExternal: true, durationSeconds: 330, moods: ["energetic", "bright"], era: "classical", instruments: ["strings"], intensity: 3 },
  { id: "track-064", title: "교향곡 40번 - 1악장 Molto Allegro", composer: "모차르트", performer: "Musopen", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Mozart_SymphonyNo.40inGMinor/WolfgangAmadeusMozart-SymphonyNo.40InGMinorK.550-01-MoltoAllegro.mp3", isExternal: true, durationSeconds: 480, moods: ["energetic", "emotional"], era: "classical", instruments: ["orchestra"], intensity: 3 },
  { id: "track-065", title: "교향곡 5번 - 1악장 운명", composer: "베토벤", performer: "Arturo Toscanini", sourceUrl: "https://archive.org/download/SymphonyNo.5/Ludwig_van_Beethoven_-_symphony_no._5_in_c_minor_op._67_-_i._allegro_con_brio.mp3", isExternal: true, durationSeconds: 450, moods: ["energetic", "emotional"], era: "classical", instruments: ["orchestra"], intensity: 3 },
  { id: "track-066", title: "교향곡 7번 - 4악장 Allegro con brio", composer: "베토벤", performer: "Philadelphia Orchestra", sourceUrl: "https://archive.org/download/Beethoven_symphony7/IV%20-%20Allegro%20con%20brio.mp3", isExternal: true, durationSeconds: 420, moods: ["energetic", "bright"], era: "classical", instruments: ["orchestra"], intensity: 3 },
];
