/**
 * 빌드 전용 원본 트랙 목록 (scripts/build-music.ts 에서만 사용).
 *
 * 3채널(피아노/클래식/재즈) 음원의 순서·메타데이터·**출처** 소스.
 * (2026-07-31: 활기찬 클래식 채널을 클래식으로 통합 — energetic 곡들은 클래식 후반부에 위치)
 * 런타임 앱은 이 파일을 import 하지 않으며 생성된 lib/music/genres.ts(자동 생성)만 사용한다.
 *
 * 2026-09-03 v5 — 출처 기반 재구축:
 *   · sourceUrl 은 실제 원본을 가리킨다(https = Musopen FLAC(archive.org)·Wikimedia Commons·Mixkit,
 *     git:<commit>:<path> = 이 저장소 이력의 최초 다운로드본). 산출물 경로가 아니다.
 *   · file 은 산출물 파일명(public/music/<file>)이자 곡의 고정 식별자.
 *   · clip 은 원본에 다른 곡이 이어 붙은 경우 잘라낼 구간(아라베스크 1번: 원본이 1+2번).
 *   · 재즈 "Dreamy Jazz"(Mixkit 645) 제거 — 646 "Groovy Jazz" 와 바이트 동일 음원(중복).
 *   · 라이선스: PD / CC0 / Mixkit Free License 우선. CC BY-SA 2.0(Advent Chamber Orchestra 2곡)은
 *     음악 시트 하단에 출처를 표기한다. 음원 교체 시 표기도 함께 갱신할 것.
 *
 * 품질 기준: 무손실(FLAC/WAV) 또는 256k 이상 원본 우선. 인코딩은 320k CBR + -18 LUFS 선형 정규화.
 * 채널 분류: channel 필드가 단일 기준 (era 는 메타데이터).
 */
export type MusicChannelId = "piano" | "classic" | "jazz";

export interface SourceTrack {
  id: string;
  title: string;
  composer: string;
  performer: string;
  /** 산출물 파일명(public/music/<file>) — 곡의 고정 식별자 */
  file: string;
  /**
   * 원본 출처. https: 원격 원본(Musopen FLAC·Wikimedia Commons·Mixkit) /
   * git:<commit>:<path>: 이 저장소 이력의 최초 다운로드본(외부 원본을 더 찾지 못한 곡)
   */
  sourceUrl: string;
  isExternal: boolean;
  /** 원본에 다른 곡이 이어 붙어 있을 때 사용할 구간(초) */
  clip?: { start?: number; end?: number };
  durationSeconds: number;
  moods: string[];
  era: string;
  instruments: string[];
  intensity: number;
  /** 병합 스트림 채널 */
  channel: MusicChannelId;
}

export const MUSIC_TRACKS: SourceTrack[] = [
  // ════ 🎹 피아노 (잔잔한 솔로 피아노) ════
  { id: "track-001", title: "골드베르크 변주곡 - Aria", composer: "바흐", performer: "Kimiko Ishizaka (Open Goldberg Variations)", file: "bach-goldberg-aria.mp3", sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7d/Goldberg_Variations_BWV_988_01_Aria.flac", isExternal: true, durationSeconds: 292, moods: ["focus", "peaceful"], era: "baroque", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-002", title: "골드베르크 변주곡 - Var.25", composer: "바흐", performer: "Shelley Katz (Musopen)", file: "bach-goldberg-var25.mp3", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Bach_GoldbergVariations/JohannSebastianBach-26-GoldbergVariationsBwv.988-Variation25.flac", isExternal: true, durationSeconds: 410, moods: ["contemplative", "emotional"], era: "baroque", instruments: ["piano"], intensity: 2, channel: "piano" },
  { id: "track-004", title: "평균율 1권 프렐류드 C장조 BWV 846", composer: "바흐", performer: "Kimiko Ishizaka (Open Well-Tempered Clavier)", file: "bach-wtc-prelude-c.mp3", sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6b/Kimiko_Ishizaka_-_Bach-_Well-Tempered_Clavier%2C_Book_1_-_01_Prelude_No._1_in_C_major%2C_BWV_846.flac", isExternal: true, durationSeconds: 135, moods: ["focus", "bright"], era: "baroque", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-201", title: "프랑스 모음곡 5번 - 사라방드", composer: "바흐", performer: "Public Domain", file: "bach-french-suite-5-sarabande.mp3", sourceUrl: "git:6ea6ddb:public/music/bach-french-suite-5-sarabande.mp3", isExternal: false, durationSeconds: 230, moods: ["peaceful", "contemplative"], era: "baroque", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-202", title: "인벤션 1번 C장조", composer: "바흐", performer: "Public Domain", file: "bach-invention-1-c-major.mp3", sourceUrl: "git:6ea6ddb:public/music/bach-invention-1-c-major.mp3", isExternal: false, durationSeconds: 65, moods: ["focus", "bright"], era: "baroque", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-203", title: "인벤션 8번 F장조", composer: "바흐", performer: "Public Domain", file: "bach-invention-8-f-major.mp3", sourceUrl: "git:6ea6ddb:public/music/bach-invention-8-f-major.mp3", isExternal: false, durationSeconds: 54, moods: ["focus", "bright"], era: "baroque", instruments: ["piano"], intensity: 2, channel: "piano" },
  { id: "track-204", title: "소나타 K.380", composer: "스카를라티", performer: "Public Domain", file: "scarlatti-sonata-k380.mp3", sourceUrl: "git:6ea6ddb:public/music/scarlatti-sonata-k380.mp3", isExternal: false, durationSeconds: 330, moods: ["bright", "peaceful"], era: "baroque", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-008", title: "월광 소나타 - 1악장", composer: "베토벤", performer: "Public Domain", file: "beethoven-moonlight-1.mp3", sourceUrl: "git:b9af403:public/music/beethoven-moonlight-1.mp3", isExternal: false, durationSeconds: 360, moods: ["contemplative", "peaceful"], era: "classical", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-097", title: "비창 소나타 - 2악장 Adagio", composer: "베토벤", performer: "Daniel Veesey", file: "beethoven-pathetique-2-adagio.mp3", sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7c/%D0%91%D0%B5%D1%82%D1%85%D0%BE%D0%B2%D0%B5%D0%BD_%D0%9B%D1%8E%D0%B4%D0%B2%D0%B8%D0%B3_%D0%92%D0%B0%D0%BD_-_%D0%A1%D0%BE%D0%BD%D0%B0%D1%82%D0%B0_8_%D0%B4%D0%BB%D1%8F_%D1%84-%D0%BD%D0%BE_%D0%9F%D0%B0%D1%82%D0%B5%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B0%D1%8F_%D0%B2_%D0%B4%D0%BE_%D0%BC%D0%B8%D0%BD%D0%BE%D1%80%D0%B5%2C_Op._13_-_2._Adagio_cantabile.wav", isExternal: true, durationSeconds: 326, moods: ["contemplative", "peaceful"], era: "classical", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-205", title: "소나타 K.545 - 2악장 Andante", composer: "모차르트", performer: "Public Domain", file: "mozart-sonata-k545-andante.mp3", sourceUrl: "git:6ea6ddb:public/music/mozart-sonata-k545-andante.mp3", isExternal: false, durationSeconds: 198, moods: ["peaceful", "relaxing"], era: "classical", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-009", title: "소나타 D.664 - 1악장", composer: "슈베르트", performer: "Paul Pitman (Musopen)", file: "schubert-allegro.mp3", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Schubert_SonataInAMajorD.664/FranzSchubert-SonataInAMajorD.664-01-AllegroModerato.flac", isExternal: true, durationSeconds: 466, moods: ["focus", "bright"], era: "romantic", instruments: ["piano"], intensity: 2, channel: "piano" },
  { id: "track-010", title: "소나타 D.664 - 2악장", composer: "슈베르트", performer: "Paul Pitman (Musopen)", file: "schubert-andante.mp3", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Schubert_SonataInAMajorD.664/FranzSchubert-SonataInAMajorD.664-02-Andante.flac", isExternal: true, durationSeconds: 290, moods: ["contemplative", "emotional"], era: "romantic", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-012", title: "녹턴 Op.9 No.2", composer: "쇼팽", performer: "Frank Levy (Musopen)", file: "chopin-nocturne-op9-2.mp3", sourceUrl: "https://archive.org/download/musopen-chopin-complete-works-flac/Nocturne%20in%20E%20flat%20major%2C%20Op.%209%20no.%202.flac", isExternal: true, durationSeconds: 270, moods: ["relaxing", "emotional"], era: "romantic", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-013", title: "녹턴 Op.27 No.2", composer: "쇼팽", performer: "Frank Levy (Musopen)", file: "chopin-nocturne-op27-2.mp3", sourceUrl: "https://archive.org/download/musopen-chopin-complete-works-flac/Nocturne%20in%20D%20flat%20major%2C%20Op.%2027%20no.%202.flac", isExternal: true, durationSeconds: 360, moods: ["relaxing", "peaceful"], era: "romantic", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-086", title: "녹턴 Op.15 No.2", composer: "쇼팽", performer: "Luke Faulkner (Musopen)", file: "chopin-nocturne-op15-2.mp3", sourceUrl: "https://archive.org/download/musopen-chopin-complete-works-flac/Nocturne%20in%20F%20sharp%20major%2C%20Op.%2015%2C%20no.%202.flac", isExternal: true, durationSeconds: 135, moods: ["relaxing", "peaceful"], era: "romantic", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-087", title: "녹턴 Op.55 No.1", composer: "쇼팽", performer: "Luke Faulkner (Musopen)", file: "chopin-nocturne-op55-1.mp3", sourceUrl: "https://archive.org/download/musopen-chopin-complete-works-flac/Nocturne%20in%20F%20minor%2C%20Op.%2055%20no.%201.flac", isExternal: true, durationSeconds: 216, moods: ["relaxing", "emotional"], era: "romantic", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-206", title: "녹턴 Op.48 No.1", composer: "쇼팽", performer: "Luke Faulkner (Musopen)", file: "chopin-nocturne-op48-1.mp3", sourceUrl: "https://archive.org/download/musopen-chopin-complete-works-flac/Nocturne%20in%20C%20minor%2C%20Op.%2048%20no.%201.flac", isExternal: true, durationSeconds: 190, moods: ["contemplative", "emotional"], era: "romantic", instruments: ["piano"], intensity: 2, channel: "piano" },
  { id: "track-014", title: "발라드 1번 Op.23", composer: "쇼팽", performer: "Frank Levy (Musopen)", file: "chopin-ballade-1.mp3", sourceUrl: "https://archive.org/download/musopen-chopin-complete-works-flac/Ballade%20no.%201%20in%20G%20minor%2C%20Op.%2023.flac", isExternal: true, durationSeconds: 540, moods: ["emotional", "contemplative"], era: "romantic", instruments: ["piano"], intensity: 3, channel: "piano" },
  { id: "track-015", title: "왈츠 Op.64 No.2", composer: "쇼팽", performer: "Olga Gurevich (Musopen)", file: "chopin-waltz-op64-2.mp3", sourceUrl: "https://archive.org/download/musopen-chopin-complete-works-flac/Waltz%20in%20C%20sharp%20minor%2C%20Op.%2064%20no.%202.flac", isExternal: true, durationSeconds: 210, moods: ["emotional", "bright"], era: "romantic", instruments: ["piano"], intensity: 2, channel: "piano" },
  { id: "track-016", title: "프렐류드 Op.28 No.4", composer: "쇼팽", performer: "Musopen", file: "chopin-prelude-op28-4.mp3", sourceUrl: "https://archive.org/download/musopen-chopin-complete-works-flac/Preludes%2C%20Op.%2028%20-%20No.%204%20%27Suffocation%27.flac", isExternal: true, durationSeconds: 120, moods: ["contemplative", "emotional"], era: "romantic", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-017", title: "프렐류드 Op.28 No.15 \"빗방울\"", composer: "쇼팽", performer: "Musopen", file: "chopin-prelude-op28-15.mp3", sourceUrl: "https://archive.org/download/musopen-chopin-complete-works-flac/Preludes%2C%20Op.%2028%20-%20No.%2015%20%27Raindrop%27.flac", isExternal: true, durationSeconds: 330, moods: ["contemplative", "peaceful"], era: "romantic", instruments: ["piano"], intensity: 2, channel: "piano" },
  { id: "track-085", title: "아베 마리아", composer: "슈베르트", performer: "Public Domain", file: "schubert-ave-maria.mp3", sourceUrl: "git:6ea6ddb:public/music/schubert-ave-maria.mp3", isExternal: false, durationSeconds: 260, moods: ["peaceful", "emotional"], era: "romantic", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-099", title: "즉흥곡 Op.90 No.3", composer: "슈베르트", performer: "Public Domain", file: "schubert-impromptu-op90-3.mp3", sourceUrl: "git:6ea6ddb:public/music/schubert-impromptu-op90-3.mp3", isExternal: false, durationSeconds: 404, moods: ["relaxing", "peaceful"], era: "romantic", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-089", title: "트로이메라이 (꿈)", composer: "슈만", performer: "Public Domain", file: "schumann-traumerei.mp3", sourceUrl: "git:6ea6ddb:public/music/schumann-traumerei.mp3", isExternal: false, durationSeconds: 152, moods: ["contemplative", "peaceful"], era: "romantic", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-090", title: "꿈 후에 (Après un rêve)", composer: "포레", performer: "Public Domain", file: "faure-apres-un-reve.mp3", sourceUrl: "git:6ea6ddb:public/music/faure-apres-un-reve.mp3", isExternal: false, durationSeconds: 174, moods: ["emotional", "contemplative"], era: "romantic", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-207", title: "위안 3번", composer: "리스트", performer: "Public Domain", file: "liszt-consolation-3.mp3", sourceUrl: "git:6ea6ddb:public/music/liszt-consolation-3.mp3", isExternal: false, durationSeconds: 283, moods: ["contemplative", "peaceful"], era: "romantic", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-019", title: "아라베스크 1번", composer: "드뷔시", performer: "Public Domain", file: "debussy-arabesque-1.mp3", sourceUrl: "git:b9af403:public/music/debussy-arabesque-1.mp3", isExternal: false, clip: { end: 255.5 }, durationSeconds: 300, moods: ["bright", "relaxing"], era: "impressionist", instruments: ["piano"], intensity: 2, channel: "piano" },
  { id: "track-020", title: "달빛 (베르가마스크 모음곡)", composer: "드뷔시", performer: "Laurens Goedhart", file: "debussy-clair-de-lune.mp3", sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/b/be/Clair_de_lune_%28Claude_Debussy%29_Suite_bergamasque.ogg", isExternal: true, durationSeconds: 300, moods: ["peaceful", "contemplative"], era: "impressionist", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-021", title: "짐노페디 1번", composer: "사티", performer: "Public Domain", file: "satie-gymnopedie-1.mp3", sourceUrl: "git:b9af403:public/music/satie-gymnopedie-1.mp3", isExternal: false, durationSeconds: 195, moods: ["peaceful", "contemplative"], era: "impressionist", instruments: ["piano"], intensity: 1, channel: "piano" },
  { id: "track-100", title: "뇨시엔느 1번", composer: "사티", performer: "Public Domain", file: "satie-gnossienne-1.mp3", sourceUrl: "git:6ea6ddb:public/music/satie-gnossienne-1.mp3", isExternal: false, durationSeconds: 269, moods: ["contemplative", "peaceful"], era: "impressionist", instruments: ["piano"], intensity: 1, channel: "piano" },

  // ════ 🎻 클래식 (현악·관현악 잔잔) ════
  { id: "track-026", title: "무반주 첼로 모음곡 1번 - 프렐류드", composer: "바흐", performer: "Pablo Casals", file: "bach-cello-suite-1-prelude.mp3", sourceUrl: "git:b9af403:public/music/bach-cello-suite-1-prelude.mp3", isExternal: false, durationSeconds: 165, moods: ["focus", "bright"], era: "baroque", instruments: ["cello"], intensity: 2, channel: "classic" },
  { id: "track-031", title: "캐논 D장조", composer: "파헬벨", performer: "Public Domain", file: "pachelbel-canon-d.mp3", sourceUrl: "git:b9af403:public/music/pachelbel-canon-d.mp3", isExternal: false, durationSeconds: 462, moods: ["relaxing", "peaceful"], era: "baroque", instruments: ["strings"], intensity: 1, channel: "classic" },
  { id: "track-082", title: "양은 풀을 뜯고 (BWV 208)", composer: "바흐", performer: "Public Domain", file: "bach-sheep-may-safely-graze.mp3", sourceUrl: "git:6ea6ddb:public/music/bach-sheep-may-safely-graze.mp3", isExternal: false, durationSeconds: 301, moods: ["peaceful", "relaxing"], era: "baroque", instruments: ["orchestra"], intensity: 1, channel: "classic" },
  { id: "track-208", title: "예수, 인간 소망의 기쁨", composer: "바흐", performer: "Public Domain", file: "bach-jesu-joy-bwv147.mp3", sourceUrl: "git:6ea6ddb:public/music/bach-jesu-joy-bwv147.mp3", isExternal: false, durationSeconds: 204, moods: ["peaceful", "bright"], era: "baroque", instruments: ["orchestra"], intensity: 1, channel: "classic" },
  { id: "track-209", title: "아다지오 G단조", composer: "알비노니", performer: "Public Domain", file: "albinoni-adagio-g-minor.mp3", sourceUrl: "git:6ea6ddb:public/music/albinoni-adagio-g-minor.mp3", isExternal: false, durationSeconds: 706, moods: ["contemplative", "emotional"], era: "baroque", instruments: ["strings"], intensity: 1, channel: "classic" },
  { id: "track-104", title: "라르고 (옴브라 마이 푸)", composer: "헨델", performer: "Public Domain", file: "handel-largo-ombra-mai-fu.mp3", sourceUrl: "git:6ea6ddb:public/music/handel-largo-ombra-mai-fu.mp3", isExternal: false, durationSeconds: 219, moods: ["peaceful", "relaxing"], era: "baroque", instruments: ["strings"], intensity: 1, channel: "classic" },
  { id: "track-210", title: "수상음악 - 에어", composer: "헨델", performer: "Public Domain", file: "handel-water-music-air.mp3", sourceUrl: "git:6ea6ddb:public/music/handel-water-music-air.mp3", isExternal: false, durationSeconds: 147, moods: ["peaceful", "relaxing"], era: "baroque", instruments: ["orchestra"], intensity: 1, channel: "classic" },
  { id: "track-211", title: "무반주 플루트 환상곡 1번", composer: "텔레만", performer: "Public Domain", file: "telemann-fantasia-1.mp3", sourceUrl: "git:6ea6ddb:public/music/telemann-fantasia-1.mp3", isExternal: false, durationSeconds: 462, moods: ["focus", "peaceful"], era: "baroque", instruments: ["flute"], intensity: 1, channel: "classic" },
  { id: "track-212", title: "정령들의 춤", composer: "글루크", performer: "Public Domain", file: "gluck-dance-blessed-spirits.mp3", sourceUrl: "git:6ea6ddb:public/music/gluck-dance-blessed-spirits.mp3", isExternal: false, durationSeconds: 384, moods: ["peaceful", "relaxing"], era: "classical", instruments: ["flute", "orchestra"], intensity: 1, channel: "classic" },
  { id: "track-213", title: "세레나데 (현악 사중주 Op.3-5)", composer: "하이든", performer: "Public Domain", file: "haydn-serenade-andante.mp3", sourceUrl: "git:6ea6ddb:public/music/haydn-serenade-andante.mp3", isExternal: false, durationSeconds: 236, moods: ["relaxing", "peaceful"], era: "classical", instruments: ["string_quartet"], intensity: 1, channel: "classic" },
  { id: "track-049", title: "아이네 클라이네 - 2악장 Romance", composer: "모차르트", performer: "Collegium Aureum", file: "mozart-eine-kleine-2-romance.mp3", sourceUrl: "git:b9af403:public/music/mozart-eine-kleine-2-romance.mp3", isExternal: false, durationSeconds: 360, moods: ["relaxing", "peaceful"], era: "classical", instruments: ["strings"], intensity: 1, channel: "classic" },
  { id: "track-056", title: "교향곡 40번 - 2악장 Andante", composer: "모차르트", performer: "Musopen Symphony", file: "mozart-symphony40-2.mp3", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Mozart_SymphonyNo.40inGMinor/WolfgangAmadeusMozart-SymphonyNo.40InGMinorK.550-02-Andante.flac", isExternal: true, durationSeconds: 480, moods: ["relaxing", "contemplative"], era: "classical", instruments: ["orchestra"], intensity: 2, channel: "classic" },
  { id: "track-088", title: "피아노 협주곡 21번 - 2악장 Andante", composer: "모차르트", performer: "Public Domain", file: "mozart-piano-concerto-21-andante.mp3", sourceUrl: "git:6ea6ddb:public/music/mozart-piano-concerto-21-andante.mp3", isExternal: false, durationSeconds: 497, moods: ["peaceful", "relaxing"], era: "classical", instruments: ["piano", "orchestra"], intensity: 1, channel: "classic" },
  { id: "track-058", title: "교향곡 3번 에로이카 - 2악장", composer: "베토벤", performer: "Musopen Symphony", file: "beethoven-eroica-2.mp3", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Beethoven_SymphonyNo.3Eroica/LudwigVanBeethoven-SymphonyNo.3InEFlatMajorEroicaOp.55-02-MarciaFunebreAdagioAssai.flac", isExternal: true, durationSeconds: 960, moods: ["contemplative", "emotional"], era: "classical", instruments: ["orchestra"], intensity: 2, channel: "classic" },
  { id: "track-096", title: "교향곡 7번 - 2악장 Allegretto", composer: "베토벤", performer: "Public Domain", file: "beethoven-symphony7-2-allegretto.mp3", sourceUrl: "git:6ea6ddb:public/music/beethoven-symphony7-2-allegretto.mp3", isExternal: false, durationSeconds: 489, moods: ["contemplative", "emotional"], era: "classical", instruments: ["orchestra"], intensity: 2, channel: "classic" },
  { id: "track-028", title: "현악 사중주 2번 - 녹턴", composer: "보로딘", performer: "Musopen String Quartet", file: "borodin-nocturne.mp3", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Borodin_StringQuartetNo.2inDMajor/AlexanderBorodin-StringQuartetNo.2InDMajor-03-NocturneAndante.flac", isExternal: true, durationSeconds: 547, moods: ["relaxing", "emotional"], era: "romantic", instruments: ["string_quartet"], intensity: 1, channel: "classic" },
  { id: "track-029", title: "아메리칸 사중주 - Lento", composer: "드보르작", performer: "Musopen String Quartet", file: "dvorak-lento.mp3", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Dvorak_StringQuartetNo.12inFMajorOp.96/AntonnDvorak-StringQuartetNo.12InFMajorOp.96American-02-Lento.flac", isExternal: true, durationSeconds: 471, moods: ["relaxing", "peaceful"], era: "romantic", instruments: ["string_quartet"], intensity: 1, channel: "classic" },
  { id: "track-030", title: "명상곡", composer: "수크", performer: "Musopen String Quartet", file: "suk-meditation.mp3", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Suk_Meditation/JosefSuk-Meditation.flac", isExternal: true, durationSeconds: 405, moods: ["contemplative", "emotional"], era: "romantic", instruments: ["strings"], intensity: 1, channel: "classic" },
  { id: "track-046", title: "페르 귄트 - 아침 기분", composer: "그리그", performer: "Musopen Symphony", file: "grieg-morning-mood.mp3", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Greig_PeerGynt/EdvardGrieg-PeerGyntSuiteNo.1Op.46-01-Morning.flac", isExternal: true, durationSeconds: 229, moods: ["bright", "peaceful"], era: "romantic", instruments: ["orchestra"], intensity: 2, channel: "classic" },
  { id: "track-047", title: "페르 귄트 - 오세의 죽음", composer: "그리그", performer: "Musopen Symphony", file: "grieg-aases-death.mp3", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Greig_PeerGynt/EdvardGrieg-PeerGyntSuiteNo.1Op.46-02-AasesDeath.flac", isExternal: true, durationSeconds: 273, moods: ["contemplative", "emotional"], era: "romantic", instruments: ["strings"], intensity: 2, channel: "classic" },
  { id: "track-083", title: "타이스의 명상곡", composer: "마스네", performer: "Public Domain", file: "massenet-thais-meditation.mp3", sourceUrl: "git:6ea6ddb:public/music/massenet-thais-meditation.mp3", isExternal: false, durationSeconds: 257, moods: ["peaceful", "contemplative"], era: "romantic", instruments: ["strings", "orchestra"], intensity: 1, channel: "classic" },
  { id: "track-084", title: "백조 (동물의 사육제)", composer: "생상스", performer: "Public Domain", file: "saint-saens-the-swan.mp3", sourceUrl: "git:6ea6ddb:public/music/saint-saens-the-swan.mp3", isExternal: false, durationSeconds: 211, moods: ["relaxing", "peaceful"], era: "romantic", instruments: ["cello", "piano"], intensity: 1, channel: "classic" },
  { id: "track-214", title: "파반", composer: "포레", performer: "Public Domain", file: "faure-pavane.mp3", sourceUrl: "git:6ea6ddb:public/music/faure-pavane.mp3", isExternal: false, durationSeconds: 434, moods: ["peaceful", "contemplative"], era: "romantic", instruments: ["orchestra"], intensity: 1, channel: "classic" },
  { id: "track-215", title: "보칼리제", composer: "라흐마니노프", performer: "Public Domain", file: "rachmaninoff-vocalise.mp3", sourceUrl: "git:6ea6ddb:public/music/rachmaninoff-vocalise.mp3", isExternal: false, clip: { start: 11.0 }, durationSeconds: 350, moods: ["emotional", "contemplative"], era: "romantic", instruments: ["orchestra"], intensity: 1, channel: "classic" },

  // ──── 舊 활기찬 클래식 (에너지·밝음) — 2026-07-31 클래식 채널로 통합 ────
  { id: "track-216", title: "브란덴부르크 협주곡 3번 - 1악장", composer: "바흐", performer: "Advent Chamber Orchestra", file: "bach-brandenburg-3-allegro.mp3", sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b0/Bach_-_Brandenburg_Concerto_No._3_-_1._Allegro.ogg", isExternal: true, durationSeconds: 336, moods: ["energetic", "bright"], era: "baroque", instruments: ["orchestra"], intensity: 3, channel: "classic" },
  { id: "track-217", title: "토카타와 푸가 D단조", composer: "바흐", performer: "Public Domain", file: "bach-toccata-fugue-d-minor.mp3", sourceUrl: "git:6ea6ddb:public/music/bach-toccata-fugue-d-minor.mp3", isExternal: false, durationSeconds: 522, moods: ["energetic", "emotional"], era: "baroque", instruments: ["organ"], intensity: 3, channel: "classic" },
  { id: "track-094", title: "수상음악 - 알라 호른파이프", composer: "헨델", performer: "U.S. Marine Band", file: "handel-water-music-alla-hornpipe.mp3", sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Handel%27s_Water_Music_-_12._Alla_hornpipe_-_Chamber_Orchestra_-_United_States_Marine_Band.opus", isExternal: true, durationSeconds: 222, moods: ["energetic", "bright"], era: "baroque", instruments: ["orchestra"], intensity: 3, channel: "classic" },
  { id: "track-063", title: "아이네 클라이네 나흐트무지크 - 1악장 Allegro", composer: "모차르트", performer: "Advent Chamber Orchestra", file: "mozart-eine-kleine-1-allegro.mp3", sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/2/24/Mozart_-_Eine_kleine_Nachtmusik_-_1._Allegro.ogg", isExternal: true, durationSeconds: 330, moods: ["energetic", "bright"], era: "classical", instruments: ["strings"], intensity: 3, channel: "classic" },
  { id: "track-064", title: "교향곡 40번 - 1악장 Molto Allegro", composer: "모차르트", performer: "Musopen Symphony", file: "mozart-symphony40-1.mp3", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Mozart_SymphonyNo.40inGMinor/WolfgangAmadeusMozart-SymphonyNo.40InGMinorK.550-01-MoltoAllegro.flac", isExternal: true, durationSeconds: 480, moods: ["energetic", "emotional"], era: "classical", instruments: ["orchestra"], intensity: 3, channel: "classic" },
  { id: "track-098", title: "교향곡 25번 - 1악장", composer: "모차르트", performer: "Public Domain", file: "mozart-symphony25-1.mp3", sourceUrl: "git:6ea6ddb:public/music/mozart-symphony25-1.mp3", isExternal: false, durationSeconds: 475, moods: ["energetic", "emotional"], era: "classical", instruments: ["orchestra"], intensity: 3, channel: "classic" },
  { id: "track-218", title: "터키 행진곡", composer: "모차르트", performer: "Public Domain", file: "mozart-turkish-march.mp3", sourceUrl: "git:6ea6ddb:public/music/mozart-turkish-march.mp3", isExternal: false, durationSeconds: 232, moods: ["energetic", "bright"], era: "classical", instruments: ["piano"], intensity: 3, channel: "classic" },
  // 2026-07-08 소스 교체: 기존 Toscanini/Philadelphia 녹음은 1930~50년대 역사 음원이라
  // 표면 잡음(지지직)이 심했음. 잡음 없는 현대 퍼블릭도메인 녹음으로 교체.
  //   · 교향곡 5번 1악장 — Wikimedia Commons, Public Domain (Musopen 녹음), .ogg
  //   · 교향곡 7번 4악장(잡음) → 에그몬트 서곡으로 교체 — Wikimedia Commons "Musopen Symphony",
  //     Public Domain, 원본 무손실 FLAC을 320k로 트랜스코딩(리포 용량). 둘 다 상업·개작 허용.
  { id: "track-065", title: "교향곡 5번 - 1악장 운명", composer: "베토벤", performer: "Musopen Symphony", file: "beethoven-symphony5-1.mp3", sourceUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Ludwig_van_Beethoven_-_symphony_no._5_in_c_minor%2C_op._67_-_i._allegro_con_brio.ogg", isExternal: true, durationSeconds: 500, moods: ["energetic", "emotional"], era: "classical", instruments: ["orchestra"], intensity: 3, channel: "classic" },
  { id: "track-066", title: "에그몬트 서곡", composer: "베토벤", performer: "Musopen Symphony", file: "beethoven-egmont-overture.mp3", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Beethoven_EgmontOvertureOp.84/LudwigVanBeethoven-EgmontOvertureOp.84.flac", isExternal: true, durationSeconds: 541, moods: ["energetic", "emotional"], era: "classical", instruments: ["orchestra"], intensity: 3, channel: "classic" },
  { id: "track-092", title: "세빌리아의 이발사 서곡", composer: "로시니", performer: "Public Domain", file: "rossini-barber-seville-overture.mp3", sourceUrl: "git:6ea6ddb:public/music/rossini-barber-seville-overture.mp3", isExternal: false, durationSeconds: 440, moods: ["energetic", "bright"], era: "classical", instruments: ["orchestra"], intensity: 3, channel: "classic" },
  { id: "track-091", title: "헝가리 무곡 5번", composer: "브람스", performer: "Public Domain", file: "brahms-hungarian-dance-5.mp3", sourceUrl: "git:6ea6ddb:public/music/brahms-hungarian-dance-5.mp3", isExternal: false, durationSeconds: 172, moods: ["energetic", "bright"], era: "romantic", instruments: ["orchestra"], intensity: 3, channel: "classic" },
  { id: "track-093", title: "꽃의 왈츠 (호두까기 인형)", composer: "차이콥스키", performer: "Public Domain", file: "tchaikovsky-waltz-of-flowers.mp3", sourceUrl: "git:6ea6ddb:public/music/tchaikovsky-waltz-of-flowers.mp3", isExternal: false, durationSeconds: 405, moods: ["energetic", "bright"], era: "romantic", instruments: ["orchestra"], intensity: 3, channel: "classic" },
  { id: "track-219", title: "현을 위한 세레나데 - 왈츠", composer: "차이콥스키", performer: "Public Domain", file: "tchaikovsky-serenade-waltz.mp3", sourceUrl: "git:6ea6ddb:public/music/tchaikovsky-serenade-waltz.mp3", isExternal: false, durationSeconds: 246, moods: ["bright", "energetic"], era: "romantic", instruments: ["strings"], intensity: 2, channel: "classic" },
  { id: "track-095", title: "산왕의 궁전에서 (페르 귄트)", composer: "그리그", performer: "Musopen Symphony", file: "grieg-hall-mountain-king.mp3", sourceUrl: "https://archive.org/download/MusopenCollectionAsFlac/Greig_PeerGynt/EdvardGrieg-PeerGyntSuiteNo.1Op.46-04-InTheHallOfTheMountainKing.flac", isExternal: true, durationSeconds: 155, moods: ["energetic", "bright"], era: "romantic", instruments: ["orchestra"], intensity: 3, channel: "classic" },

  // ════ 🎷 재즈 (35곡, Supabase Storage) ════
  { id: "track-147", title: "Beautiful Dream", composer: "Diego Nava", performer: "Diego Nava", file: "beautiful-dream.mp3", sourceUrl: "https://assets.mixkit.co/music/493/493.mp3", isExternal: true, durationSeconds: 97, moods: ["peaceful", "relaxing"], era: "jazz", instruments: ["piano", "upright_bass"], intensity: 1, channel: "jazz" },
  { id: "track-148", title: "Latin Lovers", composer: "Ahjay Stelino", performer: "Ahjay Stelino", file: "latin-lovers.mp3", sourceUrl: "https://assets.mixkit.co/music/39/39.mp3", isExternal: true, durationSeconds: 95, moods: ["relaxing", "bright"], era: "jazz", instruments: ["guitar", "piano"], intensity: 1, channel: "jazz" },
  { id: "track-149", title: "Romantic 01", composer: "Lily J", performer: "Lily J", file: "romantic-01.mp3", sourceUrl: "https://assets.mixkit.co/music/752/752.mp3", isExternal: true, durationSeconds: 99, moods: ["emotional", "peaceful"], era: "jazz", instruments: ["piano"], intensity: 1, channel: "jazz" },
  { id: "track-150", title: "Romantic Vacation", composer: "Ahjay Stelino", performer: "Ahjay Stelino", file: "romantic-vacation.mp3", sourceUrl: "https://assets.mixkit.co/music/89/89.mp3", isExternal: true, durationSeconds: 112, moods: ["relaxing", "peaceful"], era: "jazz", instruments: ["piano", "guitar"], intensity: 1, channel: "jazz" },
  { id: "track-151", title: "Smooth Like Jazz", composer: "Ahjay Stelino", performer: "Ahjay Stelino", file: "smooth-like-jazz.mp3", sourceUrl: "https://assets.mixkit.co/music/24/24.mp3", isExternal: true, durationSeconds: 158, moods: ["relaxing", "focus"], era: "jazz", instruments: ["piano", "saxophone"], intensity: 1, channel: "jazz" },
  { id: "track-152", title: "Chill Bro", composer: "Diego Nava", performer: "Diego Nava", file: "chill-bro.mp3", sourceUrl: "https://assets.mixkit.co/music/494/494.mp3", isExternal: true, durationSeconds: 100, moods: ["relaxing", "peaceful"], era: "jazz", instruments: ["piano", "upright_bass"], intensity: 1, channel: "jazz" },
  { id: "track-153", title: "Lounging By Moonlight", composer: "Ahjay Stelino", performer: "Ahjay Stelino", file: "lounging-by-moonlight.mp3", sourceUrl: "https://assets.mixkit.co/music/40/40.mp3", isExternal: true, durationSeconds: 94, moods: ["contemplative", "peaceful"], era: "jazz", instruments: ["piano", "saxophone"], intensity: 1, channel: "jazz" },
  { id: "track-154", title: "Soul Jazz", composer: "Francisco Alvear", performer: "Francisco Alvear", file: "soul-jazz.mp3", sourceUrl: "https://assets.mixkit.co/music/652/652.mp3", isExternal: true, durationSeconds: 135, moods: ["emotional", "relaxing"], era: "jazz", instruments: ["saxophone", "piano", "drums"], intensity: 2, channel: "jazz" },
  { id: "track-155", title: "Lonely in the Bar", composer: "Diego Nava", performer: "Diego Nava", file: "lonely-in-the-bar.mp3", sourceUrl: "https://assets.mixkit.co/music/518/518.mp3", isExternal: true, durationSeconds: 92, moods: ["contemplative", "emotional"], era: "jazz", instruments: ["piano", "upright_bass"], intensity: 1, channel: "jazz" },
  { id: "track-156", title: "Winter Wind", composer: "Diego Nava", performer: "Diego Nava", file: "winter-wind.mp3", sourceUrl: "https://assets.mixkit.co/music/502/502.mp3", isExternal: true, durationSeconds: 92, moods: ["contemplative", "peaceful"], era: "jazz", instruments: ["piano"], intensity: 1, channel: "jazz" },
  // 주의: 원본 jazz-1.mp3 는 v1 병합 파트 업로드가 같은 이름으로 덮어씀(2026-06-08 사고).
  // v1 스트림에서 원곡 구간(1073.685s~, 134s)을 추출해 jazz-1-track.mp3 로 복구(2026-07-07).
  { id: "track-157", title: "Jazz 1", composer: "Francisco Alvear", performer: "Francisco Alvear", file: "jazz-1-track.mp3", sourceUrl: "https://assets.mixkit.co/music/639/639.mp3", isExternal: true, durationSeconds: 134, moods: ["focus", "relaxing"], era: "jazz", instruments: ["saxophone", "piano", "drums"], intensity: 2, channel: "jazz" },
  { id: "track-158", title: "Nostalgic Night", composer: "Michael Ramir C.", performer: "Michael Ramir C.", file: "nostalgic-night.mp3", sourceUrl: "https://assets.mixkit.co/music/1112/1112.mp3", isExternal: true, durationSeconds: 125, moods: ["contemplative", "emotional"], era: "jazz", instruments: ["piano", "trumpet"], intensity: 1, channel: "jazz" },
  { id: "track-159", title: "Lo-Fi 03", composer: "Lily J", performer: "Lily J", file: "lo-fi-03.mp3", sourceUrl: "https://assets.mixkit.co/music/765/765.mp3", isExternal: true, durationSeconds: 113, moods: ["relaxing", "focus"], era: "jazz", instruments: ["piano", "drums"], intensity: 1, channel: "jazz" },
  { id: "track-160", title: "Swing is the Answer", composer: "Diego Nava", performer: "Diego Nava", file: "swing-is-the-answer.mp3", sourceUrl: "https://assets.mixkit.co/music/526/526.mp3", isExternal: true, durationSeconds: 109, moods: ["bright", "energetic"], era: "jazz", instruments: ["piano", "upright_bass", "drums"], intensity: 2, channel: "jazz" },
  { id: "track-161", title: "Where Are My Boots", composer: "Michael Ramir C.", performer: "Michael Ramir C.", file: "where-are-my-boots.mp3", sourceUrl: "https://assets.mixkit.co/music/820/820.mp3", isExternal: true, durationSeconds: 162, moods: ["relaxing", "contemplative"], era: "jazz", instruments: ["piano", "saxophone"], intensity: 1, channel: "jazz" },
  { id: "track-162", title: "Lost in a Dream", composer: "Michael Ramir C.", performer: "Michael Ramir C.", file: "lost-in-a-dream.mp3", sourceUrl: "https://assets.mixkit.co/music/1033/1033.mp3", isExternal: true, durationSeconds: 112, moods: ["contemplative", "peaceful"], era: "jazz", instruments: ["piano", "trumpet"], intensity: 1, channel: "jazz" },
  { id: "track-163", title: "Papa", composer: "Michael Ramir C.", performer: "Michael Ramir C.", file: "papa.mp3", sourceUrl: "https://assets.mixkit.co/music/879/879.mp3", isExternal: true, durationSeconds: 97, moods: ["relaxing", "peaceful"], era: "jazz", instruments: ["piano", "drums"], intensity: 1, channel: "jazz" },
  { id: "track-164", title: "You Got Jazz", composer: "Diego Nava", performer: "Diego Nava", file: "you-got-jazz.mp3", sourceUrl: "https://assets.mixkit.co/music/528/528.mp3", isExternal: true, durationSeconds: 100, moods: ["bright", "relaxing"], era: "jazz", instruments: ["piano", "upright_bass", "drums"], intensity: 2, channel: "jazz" },
  { id: "track-165", title: "Pop 03", composer: "Grigoriy Nuzhny", performer: "Grigoriy Nuzhny", file: "pop-03.mp3", sourceUrl: "https://assets.mixkit.co/music/700/700.mp3", isExternal: true, durationSeconds: 171, moods: ["relaxing", "focus"], era: "jazz", instruments: ["piano", "guitar"], intensity: 1, channel: "jazz" },
  { id: "track-166", title: "Upbeat Jazz", composer: "Francisco Alvear", performer: "Francisco Alvear", file: "upbeat-jazz.mp3", sourceUrl: "https://assets.mixkit.co/music/644/644.mp3", isExternal: true, durationSeconds: 110, moods: ["energetic", "bright"], era: "jazz", instruments: ["saxophone", "piano", "drums"], intensity: 2, channel: "jazz" },
  { id: "track-167", title: "Fun Jazz", composer: "Francisco Alvear", performer: "Francisco Alvear", file: "fun-jazz.mp3", sourceUrl: "https://assets.mixkit.co/music/647/647.mp3", isExternal: true, durationSeconds: 141, moods: ["bright", "energetic"], era: "jazz", instruments: ["saxophone", "piano", "drums"], intensity: 2, channel: "jazz" },
  { id: "track-168", title: "Slow Walk", composer: "Michael Ramir C.", performer: "Michael Ramir C.", file: "slow-walk.mp3", sourceUrl: "https://assets.mixkit.co/music/1009/1009.mp3", isExternal: true, durationSeconds: 103, moods: ["relaxing", "contemplative"], era: "jazz", instruments: ["piano", "drums"], intensity: 1, channel: "jazz" },
  { id: "track-169", title: "Feeling Good", composer: "Diego Nava", performer: "Diego Nava", file: "feeling-good.mp3", sourceUrl: "https://assets.mixkit.co/music/513/513.mp3", isExternal: true, durationSeconds: 100, moods: ["bright", "relaxing"], era: "jazz", instruments: ["piano", "upright_bass"], intensity: 1, channel: "jazz" },
  { id: "track-170", title: "Groovy Jazz", composer: "Francisco Alvear", performer: "Francisco Alvear", file: "groovy-jazz.mp3", sourceUrl: "https://assets.mixkit.co/music/646/646.mp3", isExternal: true, durationSeconds: 136, moods: ["energetic", "bright"], era: "jazz", instruments: ["saxophone", "piano", "drums"], intensity: 2, channel: "jazz" },
  { id: "track-172", title: "Close the Lights", composer: "Michael Ramir C.", performer: "Michael Ramir C.", file: "close-the-lights.mp3", sourceUrl: "https://assets.mixkit.co/music/826/826.mp3", isExternal: true, durationSeconds: 116, moods: ["contemplative", "emotional"], era: "jazz", instruments: ["piano", "drums"], intensity: 1, channel: "jazz" },
  { id: "track-173", title: "Space Bird", composer: "Diego Nava", performer: "Diego Nava", file: "space-bird.mp3", sourceUrl: "https://assets.mixkit.co/music/500/500.mp3", isExternal: true, durationSeconds: 109, moods: ["contemplative", "peaceful"], era: "jazz", instruments: ["piano", "upright_bass"], intensity: 1, channel: "jazz" },
  { id: "track-174", title: "Funk Jazz", composer: "Francisco Alvear", performer: "Francisco Alvear", file: "funk-jazz.mp3", sourceUrl: "https://assets.mixkit.co/music/643/643.mp3", isExternal: true, durationSeconds: 136, moods: ["energetic", "bright"], era: "jazz", instruments: ["saxophone", "piano", "drums", "guitar"], intensity: 2, channel: "jazz" },
  { id: "track-175", title: "Romantic 02", composer: "Lily J", performer: "Lily J", file: "romantic-02.mp3", sourceUrl: "https://assets.mixkit.co/music/753/753.mp3", isExternal: true, durationSeconds: 104, moods: ["emotional", "peaceful"], era: "jazz", instruments: ["piano"], intensity: 1, channel: "jazz" },
  { id: "track-176", title: "Lost in Dreams", composer: "Ahjay Stelino", performer: "Ahjay Stelino", file: "lost-in-dreams.mp3", sourceUrl: "https://assets.mixkit.co/music/26/26.mp3", isExternal: true, durationSeconds: 124, moods: ["contemplative", "relaxing"], era: "jazz", instruments: ["piano", "saxophone"], intensity: 1, channel: "jazz" },
  { id: "track-177", title: "Red Moon", composer: "Diego Nava", performer: "Diego Nava", file: "red-moon.mp3", sourceUrl: "https://assets.mixkit.co/music/499/499.mp3", isExternal: true, durationSeconds: 104, moods: ["contemplative", "emotional"], era: "jazz", instruments: ["piano", "upright_bass"], intensity: 1, channel: "jazz" },
  { id: "track-178", title: "Majestic", composer: "Diego Nava", performer: "Diego Nava", file: "majestic.mp3", sourceUrl: "https://assets.mixkit.co/music/475/475.mp3", isExternal: true, durationSeconds: 109, moods: ["relaxing", "bright"], era: "jazz", instruments: ["piano", "upright_bass"], intensity: 1, channel: "jazz" },
  { id: "track-179", title: "Im Hungry", composer: "Michael Ramir C.", performer: "Michael Ramir C.", file: "im-hungry.mp3", sourceUrl: "https://assets.mixkit.co/music/808/808.mp3", isExternal: true, durationSeconds: 110, moods: ["energetic", "bright"], era: "jazz", instruments: ["piano", "drums", "saxophone"], intensity: 2, channel: "jazz" },
  { id: "track-180", title: "Yo Chucky", composer: "Michael Ramir C.", performer: "Michael Ramir C.", file: "yo-chucky.mp3", sourceUrl: "https://assets.mixkit.co/music/861/861.mp3", isExternal: true, durationSeconds: 97, moods: ["energetic", "bright"], era: "jazz", instruments: ["piano", "drums"], intensity: 2, channel: "jazz" },
  { id: "track-181", title: "Pop 05", composer: "Grigoriy Nuzhny", performer: "Grigoriy Nuzhny", file: "pop-05.mp3", sourceUrl: "https://assets.mixkit.co/music/695/695.mp3", isExternal: true, durationSeconds: 154, moods: ["relaxing", "focus"], era: "jazz", instruments: ["piano", "guitar"], intensity: 1, channel: "jazz" },
];
